/* DSblock model generated by Dymola from Modelica model vankor11 */

#include <matrixop.h>
/* Prototypes for functions used in model */
/* Codes used in model */
/* DSblock C-code: */

#include <moutil.c>
#include <dsblock1.c>

/* Define variable names. */

#define Sections_
#define G1_G_TgenOff  Parameter(0)
#define G1_G_dTgenOff  Parameter(1)
#define G1_G_Pg  Parameter(2)
#define G1_G_Qg  Parameter(3)
#define G1_G_Ut  Parameter(4)
#define G1_G_Xd  Parameter(5)
#define G1_G_Xq  Parameter(6)
#define G1_G_Xs  Parameter(7)
#define G1_G_X1d  Parameter(8)
#define G1_G_X2d  Parameter(9)
#define G1_G_X2q  Parameter(10)
#define G1_G_Rf  Parameter(11)
#define G1_G_R1d  Parameter(12)
#define G1_G_R1q  Parameter(13)
#define G1_G_Tj  Parameter(14)
#define G1_G_Xt  Parameter(15)
#define G1_G_Sigma  Parameter(16)
#define G1_G_TauC  Parameter(17)
#define G1_G_Mt__max  Parameter(18)
#define G1_G_Mt__min  Parameter(19)
#define G1_G_dEr  Variable(0)
#define G1_G_PI  Variable(1)
#define G1_G_Wc  Variable(2)
#define G1_G_Ra  Variable(3)
#define G1_G_Rt  Variable(4)
#define G1_G_EQ  Variable(5)
#define G1_G_Dg  Variable(6)
#define G1_G_Uq  Variable(7)
#define G1_G_Ud  Variable(8)
#define G1_G_Id  Variable(9)
#define G1_G_Iq  Variable(10)
#define G1_G_Mt  Variable(11)
#define G1_G_Eiq  Variable(12)
#define G1_G_Ir  Variable(13)
#define G1_G_Uf  Variable(14)
#define G1_G_Eq  Variable(15)
#define G1_G_Er0  Variable(16)
#define G1_G_PsiR  Variable(17)
#define G1_G_PsiRD  Variable(18)
#define G1_G_PsiRQ  Variable(19)
#define G1_G_Er__max  Variable(20)
#define G1_G_Er__min  Variable(21)
#define G1_G_Uf__full  Variable(22)
#define G1_G_Xad  Variable(23)
#define G1_G_Xaq  Variable(24)
#define G1_G_X2dt  Variable(25)
#define G1_G_X2qt  Variable(26)
#define G1_G_Rs  Variable(27)
#define G1_G_Xsf  Variable(28)
#define G1_G_Xs1d  Variable(29)
#define G1_G_Xs1q  Variable(30)
#define G1_G_X1  Variable(31)
#define G1_G_X2  Variable(32)
#define G1_G_X3  Variable(33)
#define G1_G_Ugen  Variable(34)
#define G1_G_Mu0  Variable(35)
#define G1_G_Ro  Variable(36)
#define G1_G_Mu  State(0)
#define G1_G_der_Mu  Derivative(0)
#define G1_G_Mt__pp  Variable(37)
#define G1_G_Pgen  Variable(38)
#define G1_G_Qgen  Variable(39)
#define G1_G_DeltaIJ  Variable(40)
#define G1_G_Yr  State(1)
#define G1_G_der_Yr  Derivative(1)
#define G1_G_Yrd  State(2)
#define G1_G_der_Yrd  Derivative(2)
#define G1_G_Yrq  State(3)
#define G1_G_der_Yrq  Derivative(3)
#define G1_G_s  State(4)
#define G1_G_der_s  Derivative(4)
#define G1_G_Me  Variable(41)
#define G1_G_Yad  Variable(42)
#define G1_G_Yaq  Variable(43)
#define G1_G_iq  Variable(44)
#define G1_G_id  Variable(45)
#define G1_G_ir  Variable(46)
#define G1_G_ird  Variable(47)
#define G1_G_irq  Variable(48)
#define G1_G_E11d  Variable(49)
#define G1_G_E11q  Variable(50)
#define G1_AVR_K0u  Parameter(20)
#define G1_AVR_K1u  Parameter(21)
#define G1_AVR_K0w  Parameter(22)
#define G1_AVR_K1w  Parameter(23)
#define G1_AVR_K1if  Parameter(24)
#define G1_AVR_DL0  Parameter(25)
#define G1_AVR_Tokp  Parameter(26)
#define G1_AVR_T0u  Variable(51)
#define G1_AVR_T1u  Variable(52)
#define G1_AVR_Tfb  Variable(53)
#define G1_AVR_T0w  Variable(54)
#define G1_AVR_T1w  Variable(55)
#define G1_AVR_T1if  Variable(56)
#define G1_AVR_VoltageDeviation_b  &Variable(57)
#define G1_AVR_VoltageDeviation_b_1  Variable(57)
#define G1_AVR_VoltageDeviation_a  &Variable(58)
#define G1_AVR_VoltageDeviation_a_1  Variable(58)
#define G1_AVR_VoltageDeviation_a_2  Variable(59)
#define G1_AVR_VoltageDeviation_x_1  State(5)
#define G1_AVR_VoltageDeviation_der_x_1  Derivative(5)
#define G1_AVR_VoltageDeviation_na  Variable(60)
#define G1_AVR_VoltageDeviation_nb  Variable(61)
#define G1_AVR_VoltageDeviation_nx  Variable(62)
#define G1_AVR_VoltageDeviation_u  Variable(63)
#define G1_AVR_VoltageDeviation_y  Variable(64)
#define G1_AVR_VoltageDerivative_b  &Variable(65)
#define G1_AVR_VoltageDerivative_b_1  Variable(65)
#define G1_AVR_VoltageDerivative_b_2  Variable(66)
#define G1_AVR_VoltageDerivative_a  &Variable(67)
#define G1_AVR_VoltageDerivative_a_1  Variable(67)
#define G1_AVR_VoltageDerivative_a_2  Variable(68)
#define G1_AVR_VoltageDerivative_x_1  State(6)
#define G1_AVR_VoltageDerivative_der_x_1  Derivative(6)
#define G1_AVR_VoltageDerivative_na  Variable(69)
#define G1_AVR_VoltageDerivative_nb  Variable(70)
#define G1_AVR_VoltageDerivative_nx  Variable(71)
#define G1_AVR_VoltageDerivative_y  Variable(72)
#define G1_AVR_FrequencyBlockD_b  &Parameter(27)
#define G1_AVR_FrequencyBlockD_b_1  Parameter(27)
#define G1_AVR_FrequencyBlockD_a  &Variable(73)
#define G1_AVR_FrequencyBlockD_a_1  Variable(73)
#define G1_AVR_FrequencyBlockD_a_2  Variable(74)
#define G1_AVR_FrequencyBlockD_x_1  State(7)
#define G1_AVR_FrequencyBlockD_der_x_1  Derivative(7)
#define G1_AVR_FrequencyBlockD_na  Variable(75)
#define G1_AVR_FrequencyBlockD_nb  Variable(76)
#define G1_AVR_FrequencyBlockD_nx  Variable(77)
#define G1_AVR_FrequencyBlockD_u  Variable(78)
#define G1_AVR_FrequencyBlockD_y  Variable(79)
#define G1_AVR_FrequencyBlockU_b  &Parameter(28)
#define G1_AVR_FrequencyBlockU_b_1  Parameter(28)
#define G1_AVR_FrequencyBlockU_b_2  Parameter(29)
#define G1_AVR_FrequencyBlockU_a  &Variable(80)
#define G1_AVR_FrequencyBlockU_a_1  Variable(80)
#define G1_AVR_FrequencyBlockU_a_2  Variable(81)
#define G1_AVR_FrequencyBlockU_x_1  State(8)
#define G1_AVR_FrequencyBlockU_der_x_1  Derivative(8)
#define G1_AVR_FrequencyBlockU_na  Variable(82)
#define G1_AVR_FrequencyBlockU_nb  Variable(83)
#define G1_AVR_FrequencyBlockU_nx  Variable(84)
#define G1_AVR_FrequencyBlockU_u  Variable(85)
#define G1_AVR_FrequencyBlockU_y  Variable(86)
#define G1_AVR_FrequencyDeviation_b  &Variable(87)
#define G1_AVR_FrequencyDeviation_b_1  Variable(87)
#define G1_AVR_FrequencyDeviation_b_2  Variable(88)
#define G1_AVR_FrequencyDeviation_a  &Variable(89)
#define G1_AVR_FrequencyDeviation_a_1  Variable(89)
#define G1_AVR_FrequencyDeviation_a_2  Variable(90)
#define G1_AVR_FrequencyDeviation_x_1  State(9)
#define G1_AVR_FrequencyDeviation_der_x_1  Derivative(9)
#define G1_AVR_FrequencyDeviation_na  Variable(91)
#define G1_AVR_FrequencyDeviation_nb  Variable(92)
#define G1_AVR_FrequencyDeviation_nx  Variable(93)
#define G1_AVR_FrequencyDeviation_u  Variable(94)
#define G1_AVR_FrequencyDeviation_y  Variable(95)
#define G1_AVR_FrequencyDerivative_b  &Variable(96)
#define G1_AVR_FrequencyDerivative_b_1  Variable(96)
#define G1_AVR_FrequencyDerivative_b_2  Variable(97)
#define G1_AVR_FrequencyDerivative_a  &Variable(98)
#define G1_AVR_FrequencyDerivative_a_1  Variable(98)
#define G1_AVR_FrequencyDerivative_a_2  Variable(99)
#define G1_AVR_FrequencyDerivative_x_1  State(10)
#define G1_AVR_FrequencyDerivative_der_x_1  Derivative(10)
#define G1_AVR_FrequencyDerivative_na  Variable(100)
#define G1_AVR_FrequencyDerivative_nb  Variable(101)
#define G1_AVR_FrequencyDerivative_nx  Variable(102)
#define G1_AVR_FrequencyDerivative_y  Variable(103)
#define G1_AVR_ExcitationCurrent_b  &Variable(104)
#define G1_AVR_ExcitationCurrent_b_1  Variable(104)
#define G1_AVR_ExcitationCurrent_b_2  Variable(105)
#define G1_AVR_ExcitationCurrent_a  &Variable(106)
#define G1_AVR_ExcitationCurrent_a_1  Variable(106)
#define G1_AVR_ExcitationCurrent_a_2  Variable(107)
#define G1_AVR_ExcitationCurrent_x_1  State(11)
#define G1_AVR_ExcitationCurrent_der_x_1  Derivative(11)
#define G1_AVR_ExcitationCurrent_na  Variable(108)
#define G1_AVR_ExcitationCurrent_nb  Variable(109)
#define G1_AVR_ExcitationCurrent_nx  Variable(110)
#define G1_AVR_ExcitationCurrent_u  Variable(111)
#define G1_AVR_ExcitationCurrent_y  Variable(112)
#define G1_AVR_SimpleExciter_b  &Parameter(30)
#define G1_AVR_SimpleExciter_b_1  Parameter(30)
#define G1_AVR_SimpleExciter_a  &Variable(113)
#define G1_AVR_SimpleExciter_a_1  Variable(113)
#define G1_AVR_SimpleExciter_a_2  Variable(114)
#define G1_AVR_SimpleExciter_x_1  State(12)
#define G1_AVR_SimpleExciter_der_x_1  Derivative(12)
#define G1_AVR_SimpleExciter_na  Variable(115)
#define G1_AVR_SimpleExciter_nb  Variable(116)
#define G1_AVR_SimpleExciter_nx  Variable(117)
#define G1_AVR_SimpleExciter_u  Variable(118)
#define L0102_Rline  Parameter(31)
#define L0102_Xline  Parameter(32)
#define L0102_Bline  Parameter(33)
#define L0102_TLineOff  Parameter(34)
#define L0102_dTLineOff  Parameter(35)
#define L0102_Koff  Parameter(36)
#define L0102_U1d  Variable(119)
#define L0102_U1q  Variable(120)
#define L0102_U2d  Variable(121)
#define L0102_U2q  Variable(122)
#define L0102_I12d  Variable(123)
#define L0102_I12q  Variable(124)
#define L0102_I12m  Variable(125)
#define L0102_U1m  Variable(126)
#define L0102_U2m  Variable(127)
#define L0102_I1d  Variable(128)
#define L0102_I1q  Variable(129)
#define L0102_I2d  Variable(130)
#define L0102_I2q  Variable(131)
#define L0102_Idc1  Variable(132)
#define L0102_Iqc1  Variable(133)
#define L0102_Idc2  Variable(134)
#define L0102_Iqc2  Variable(135)
#define L0102_DU1  Variable(136)
#define L0102_DU2  Variable(137)
#define L0102_Bnn  Variable(138)
#define L0102_P1  Variable(139)
#define L0102_Q1  Variable(140)
#define L0102_P2  Variable(141)
#define L0102_Q2  Variable(142)
#define L0102_RL  Variable(143)
#define L0102_XL  Variable(144)
#define L0102_BL  Variable(145)
#define SM2_G_TgenOff  Parameter(37)
#define SM2_G_dTgenOff  Parameter(38)
#define SM2_G_Pg  Parameter(39)
#define SM2_G_Qg  Parameter(40)
#define SM2_G_Ut  Parameter(41)
#define SM2_G_Xd  Parameter(42)
#define SM2_G_Xq  Parameter(43)
#define SM2_G_Xs  Parameter(44)
#define SM2_G_X1d  Parameter(45)
#define SM2_G_X2d  Parameter(46)
#define SM2_G_X2q  Parameter(47)
#define SM2_G_Rf  Parameter(48)
#define SM2_G_R1d  Parameter(49)
#define SM2_G_R1q  Parameter(50)
#define SM2_G_Tj  Parameter(51)
#define SM2_G_Xt  Parameter(52)
#define SM2_G_Sigma  Parameter(53)
#define SM2_G_TauC  Parameter(54)
#define SM2_G_Mt__max  Parameter(55)
#define SM2_G_Mt__min  Parameter(56)
#define SM2_G_dEr  Variable(146)
#define SM2_G_PI  Variable(147)
#define SM2_G_Wc  Variable(148)
#define SM2_G_Ra  Variable(149)
#define SM2_G_Rt  Variable(150)
#define SM2_G_EQ  Variable(151)
#define SM2_G_Dg  Variable(152)
#define SM2_G_Uq  Variable(153)
#define SM2_G_Ud  Variable(154)
#define SM2_G_Id  Variable(155)
#define SM2_G_Iq  Variable(156)
#define SM2_G_Mt  Variable(157)
#define SM2_G_Eiq  Variable(158)
#define SM2_G_Ir  Variable(159)
#define SM2_G_Uf  Variable(160)
#define SM2_G_Eq  Variable(161)
#define SM2_G_Er0  Variable(162)
#define SM2_G_PsiR  Variable(163)
#define SM2_G_PsiRD  Variable(164)
#define SM2_G_PsiRQ  Variable(165)
#define SM2_G_Er__max  Variable(166)
#define SM2_G_Er__min  Variable(167)
#define SM2_G_Uf__full  Variable(168)
#define SM2_G_Xad  Variable(169)
#define SM2_G_Xaq  Variable(170)
#define SM2_G_X2dt  Variable(171)
#define SM2_G_X2qt  Variable(172)
#define SM2_G_Rs  Variable(173)
#define SM2_G_Xsf  Variable(174)
#define SM2_G_Xs1d  Variable(175)
#define SM2_G_Xs1q  Variable(176)
#define SM2_G_X1  Variable(177)
#define SM2_G_X2  Variable(178)
#define SM2_G_X3  Variable(179)
#define SM2_G_Ugen  Variable(180)
#define SM2_G_Mu0  Variable(181)
#define SM2_G_Ro  Variable(182)
#define SM2_G_Mu  State(13)
#define SM2_G_der_Mu  Derivative(13)
#define SM2_G_Mt__pp  Variable(183)
#define SM2_G_Pgen  Variable(184)
#define SM2_G_Qgen  Variable(185)
#define SM2_G_IdG  Variable(186)
#define SM2_G_IqG  Variable(187)
#define SM2_G_Yr  State(14)
#define SM2_G_der_Yr  Derivative(14)
#define SM2_G_Yrd  State(15)
#define SM2_G_der_Yrd  Derivative(15)
#define SM2_G_Yrq  State(16)
#define SM2_G_der_Yrq  Derivative(16)
#define SM2_G_s  State(17)
#define SM2_G_der_s  Derivative(17)
#define SM2_G_Me  Variable(188)
#define SM2_G_Yad  Variable(189)
#define SM2_G_Yaq  Variable(190)
#define SM2_G_iq  Variable(191)
#define SM2_G_id  Variable(192)
#define SM2_G_ir  Variable(193)
#define SM2_G_ird  Variable(194)
#define SM2_G_irq  Variable(195)
#define SM2_G_ud  Variable(196)
#define SM2_G_uq  Variable(197)
#define SM2_G_E11d  Variable(198)
#define SM2_G_E11q  Variable(199)
#define SM2_AVR_K0u  Parameter(57)
#define SM2_AVR_K1u  Parameter(58)
#define SM2_AVR_K0w  Parameter(59)
#define SM2_AVR_K1w  Parameter(60)
#define SM2_AVR_K1if  Parameter(61)
#define SM2_AVR_DL0  Parameter(62)
#define SM2_AVR_Tokp  Parameter(63)
#define SM2_AVR_T0u  Variable(200)
#define SM2_AVR_T1u  Variable(201)
#define SM2_AVR_Tfb  Variable(202)
#define SM2_AVR_T0w  Variable(203)
#define SM2_AVR_T1w  Variable(204)
#define SM2_AVR_T1if  Variable(205)
#define SM2_AVR_VoltageDeviation_b  &Variable(206)
#define SM2_AVR_VoltageDeviation_b_1  Variable(206)
#define SM2_AVR_VoltageDeviation_a  &Variable(207)
#define SM2_AVR_VoltageDeviation_a_1  Variable(207)
#define SM2_AVR_VoltageDeviation_a_2  Variable(208)
#define SM2_AVR_VoltageDeviation_x_1  State(18)
#define SM2_AVR_VoltageDeviation_der_x_1  Derivative(18)
#define SM2_AVR_VoltageDeviation_na  Variable(209)
#define SM2_AVR_VoltageDeviation_nb  Variable(210)
#define SM2_AVR_VoltageDeviation_nx  Variable(211)
#define SM2_AVR_VoltageDeviation_u  Variable(212)
#define SM2_AVR_VoltageDeviation_y  Variable(213)
#define SM2_AVR_VoltageDerivative_b  &Variable(214)
#define SM2_AVR_VoltageDerivative_b_1  Variable(214)
#define SM2_AVR_VoltageDerivative_b_2  Variable(215)
#define SM2_AVR_VoltageDerivative_a  &Variable(216)
#define SM2_AVR_VoltageDerivative_a_1  Variable(216)
#define SM2_AVR_VoltageDerivative_a_2  Variable(217)
#define SM2_AVR_VoltageDerivative_x_1  State(19)
#define SM2_AVR_VoltageDerivative_der_x_1  Derivative(19)
#define SM2_AVR_VoltageDerivative_na  Variable(218)
#define SM2_AVR_VoltageDerivative_nb  Variable(219)
#define SM2_AVR_VoltageDerivative_nx  Variable(220)
#define SM2_AVR_VoltageDerivative_y  Variable(221)
#define SM2_AVR_FrequencyBlockD_b  &Parameter(64)
#define SM2_AVR_FrequencyBlockD_b_1  Parameter(64)
#define SM2_AVR_FrequencyBlockD_a  &Variable(222)
#define SM2_AVR_FrequencyBlockD_a_1  Variable(222)
#define SM2_AVR_FrequencyBlockD_a_2  Variable(223)
#define SM2_AVR_FrequencyBlockD_x_1  State(20)
#define SM2_AVR_FrequencyBlockD_der_x_1  Derivative(20)
#define SM2_AVR_FrequencyBlockD_na  Variable(224)
#define SM2_AVR_FrequencyBlockD_nb  Variable(225)
#define SM2_AVR_FrequencyBlockD_nx  Variable(226)
#define SM2_AVR_FrequencyBlockD_u  Variable(227)
#define SM2_AVR_FrequencyBlockD_y  Variable(228)
#define SM2_AVR_FrequencyBlockU_b  &Parameter(65)
#define SM2_AVR_FrequencyBlockU_b_1  Parameter(65)
#define SM2_AVR_FrequencyBlockU_b_2  Parameter(66)
#define SM2_AVR_FrequencyBlockU_a  &Variable(229)
#define SM2_AVR_FrequencyBlockU_a_1  Variable(229)
#define SM2_AVR_FrequencyBlockU_a_2  Variable(230)
#define SM2_AVR_FrequencyBlockU_x_1  State(21)
#define SM2_AVR_FrequencyBlockU_der_x_1  Derivative(21)
#define SM2_AVR_FrequencyBlockU_na  Variable(231)
#define SM2_AVR_FrequencyBlockU_nb  Variable(232)
#define SM2_AVR_FrequencyBlockU_nx  Variable(233)
#define SM2_AVR_FrequencyBlockU_u  Variable(234)
#define SM2_AVR_FrequencyBlockU_y  Variable(235)
#define SM2_AVR_FrequencyDeviation_b  &Variable(236)
#define SM2_AVR_FrequencyDeviation_b_1  Variable(236)
#define SM2_AVR_FrequencyDeviation_b_2  Variable(237)
#define SM2_AVR_FrequencyDeviation_a  &Variable(238)
#define SM2_AVR_FrequencyDeviation_a_1  Variable(238)
#define SM2_AVR_FrequencyDeviation_a_2  Variable(239)
#define SM2_AVR_FrequencyDeviation_x_1  State(22)
#define SM2_AVR_FrequencyDeviation_der_x_1  Derivative(22)
#define SM2_AVR_FrequencyDeviation_na  Variable(240)
#define SM2_AVR_FrequencyDeviation_nb  Variable(241)
#define SM2_AVR_FrequencyDeviation_nx  Variable(242)
#define SM2_AVR_FrequencyDeviation_u  Variable(243)
#define SM2_AVR_FrequencyDeviation_y  Variable(244)
#define SM2_AVR_FrequencyDerivative_b  &Variable(245)
#define SM2_AVR_FrequencyDerivative_b_1  Variable(245)
#define SM2_AVR_FrequencyDerivative_b_2  Variable(246)
#define SM2_AVR_FrequencyDerivative_a  &Variable(247)
#define SM2_AVR_FrequencyDerivative_a_1  Variable(247)
#define SM2_AVR_FrequencyDerivative_a_2  Variable(248)
#define SM2_AVR_FrequencyDerivative_x_1  State(23)
#define SM2_AVR_FrequencyDerivative_der_x_1  Derivative(23)
#define SM2_AVR_FrequencyDerivative_na  Variable(249)
#define SM2_AVR_FrequencyDerivative_nb  Variable(250)
#define SM2_AVR_FrequencyDerivative_nx  Variable(251)
#define SM2_AVR_FrequencyDerivative_y  Variable(252)
#define SM2_AVR_ExcitationCurrent_b  &Variable(253)
#define SM2_AVR_ExcitationCurrent_b_1  Variable(253)
#define SM2_AVR_ExcitationCurrent_b_2  Variable(254)
#define SM2_AVR_ExcitationCurrent_a  &Variable(255)
#define SM2_AVR_ExcitationCurrent_a_1  Variable(255)
#define SM2_AVR_ExcitationCurrent_a_2  Variable(256)
#define SM2_AVR_ExcitationCurrent_x_1  State(24)
#define SM2_AVR_ExcitationCurrent_der_x_1  Derivative(24)
#define SM2_AVR_ExcitationCurrent_na  Variable(257)
#define SM2_AVR_ExcitationCurrent_nb  Variable(258)
#define SM2_AVR_ExcitationCurrent_nx  Variable(259)
#define SM2_AVR_ExcitationCurrent_u  Variable(260)
#define SM2_AVR_ExcitationCurrent_y  Variable(261)
#define SM2_AVR_SimpleExciter_b  &Parameter(67)
#define SM2_AVR_SimpleExciter_b_1  Parameter(67)
#define SM2_AVR_SimpleExciter_a  &Variable(262)
#define SM2_AVR_SimpleExciter_a_1  Variable(262)
#define SM2_AVR_SimpleExciter_a_2  Variable(263)
#define SM2_AVR_SimpleExciter_x_1  State(25)
#define SM2_AVR_SimpleExciter_der_x_1  Derivative(25)
#define SM2_AVR_SimpleExciter_na  Variable(264)
#define SM2_AVR_SimpleExciter_nb  Variable(265)
#define SM2_AVR_SimpleExciter_nx  Variable(266)
#define SM2_AVR_SimpleExciter_u  Variable(267)
#define KZ1_Bn  Parameter(68)
#define KZ1_TkzOn  Parameter(69)
#define KZ1_dTkzOn  Parameter(70)
#define KZ1_id  Variable(268)
#define KZ1_iq  Variable(269)
#define KZ2_Bn  Parameter(71)
#define KZ2_TkzOn  Parameter(72)
#define KZ2_dTkzOn  Parameter(73)
#define KZ2_id  Variable(270)
#define KZ2_iq  Variable(271)
#define delta__G1__SM2  State(26)
#define der_delta__G1__SM2  Derivative(26)

TranslatedEquations

InitialSection
G1_G_PI = 3.14159265358979;
G1_G_Wc = 314.159265358979;
G1_G_Ra = 0;
G1_G_Rt = 0;
G1_AVR_T0u = 0.02;
G1_AVR_T1u = 0.039;
G1_AVR_Tfb = 0.07;
G1_AVR_T0w = 1;
G1_AVR_T1w = 0.026;
G1_AVR_T1if = 0.03;
G1_AVR_VoltageDeviation_a_1 = 0.02;
G1_AVR_VoltageDeviation_a_2 = 1;
G1_AVR_VoltageDeviation_na = 2;
G1_AVR_VoltageDeviation_nb = 1;
G1_AVR_VoltageDeviation_nx = 1;
G1_AVR_VoltageDerivative_b_2 = 0;
G1_AVR_VoltageDerivative_a_1 = 0.039;
G1_AVR_VoltageDerivative_a_2 = 1;
G1_AVR_VoltageDerivative_na = 2;
G1_AVR_VoltageDerivative_nb = 2;
G1_AVR_VoltageDerivative_nx = 1;
G1_AVR_FrequencyBlockD_a_1 = 0.07;
G1_AVR_FrequencyBlockD_a_2 = 1;
G1_AVR_FrequencyBlockD_na = 2;
G1_AVR_FrequencyBlockD_nb = 1;
G1_AVR_FrequencyBlockD_nx = 1;
G1_AVR_FrequencyBlockU_a_1 = 0.07;
G1_AVR_FrequencyBlockU_a_2 = 1;
G1_AVR_FrequencyBlockU_na = 2;
G1_AVR_FrequencyBlockU_nb = 2;
G1_AVR_FrequencyBlockU_nx = 1;
G1_AVR_FrequencyDeviation_b_2 = 0;
G1_AVR_FrequencyDeviation_a_1 = 1;
G1_AVR_FrequencyDeviation_a_2 = 1;
G1_AVR_FrequencyDeviation_na = 2;
G1_AVR_FrequencyDeviation_nb = 2;
G1_AVR_FrequencyDeviation_nx = 1;
G1_AVR_FrequencyDerivative_b_2 = 0;
G1_AVR_FrequencyDerivative_a_1 = 0.026;
G1_AVR_FrequencyDerivative_a_2 = 1;
G1_AVR_FrequencyDerivative_na = 2;
G1_AVR_FrequencyDerivative_nb = 2;
G1_AVR_FrequencyDerivative_nx = 1;
G1_AVR_ExcitationCurrent_b_2 = 0;
G1_AVR_ExcitationCurrent_a_1 = 0.03;
G1_AVR_ExcitationCurrent_a_2 = 1;
G1_AVR_ExcitationCurrent_na = 2;
G1_AVR_ExcitationCurrent_nb = 2;
G1_AVR_ExcitationCurrent_nx = 1;
G1_AVR_SimpleExciter_a_2 = 1;
G1_AVR_SimpleExciter_na = 2;
G1_AVR_SimpleExciter_nb = 1;
G1_AVR_SimpleExciter_nx = 1;
SM2_G_PI = 3.14159265358979;
SM2_G_Wc = 314.159265358979;
SM2_G_Ra = 0;
SM2_G_Rt = 0;
SM2_AVR_T0u = 0.02;
SM2_AVR_T1u = 0.039;
SM2_AVR_Tfb = 0.07;
SM2_AVR_T0w = 1;
SM2_AVR_T1w = 0.026;
SM2_AVR_T1if = 0.03;
SM2_AVR_VoltageDeviation_a_1 = 0.02;
SM2_AVR_VoltageDeviation_a_2 = 1;
SM2_AVR_VoltageDeviation_na = 2;
SM2_AVR_VoltageDeviation_nb = 1;
SM2_AVR_VoltageDeviation_nx = 1;
SM2_AVR_VoltageDerivative_b_2 = 0;
SM2_AVR_VoltageDerivative_a_1 = 0.039;
SM2_AVR_VoltageDerivative_a_2 = 1;
SM2_AVR_VoltageDerivative_na = 2;
SM2_AVR_VoltageDerivative_nb = 2;
SM2_AVR_VoltageDerivative_nx = 1;
SM2_AVR_FrequencyBlockD_a_1 = 0.07;
SM2_AVR_FrequencyBlockD_a_2 = 1;
SM2_AVR_FrequencyBlockD_na = 2;
SM2_AVR_FrequencyBlockD_nb = 1;
SM2_AVR_FrequencyBlockD_nx = 1;
SM2_AVR_FrequencyBlockU_a_1 = 0.07;
SM2_AVR_FrequencyBlockU_a_2 = 1;
SM2_AVR_FrequencyBlockU_na = 2;
SM2_AVR_FrequencyBlockU_nb = 2;
SM2_AVR_FrequencyBlockU_nx = 1;
SM2_AVR_FrequencyDeviation_b_2 = 0;
SM2_AVR_FrequencyDeviation_a_1 = 1;
SM2_AVR_FrequencyDeviation_a_2 = 1;
SM2_AVR_FrequencyDeviation_na = 2;
SM2_AVR_FrequencyDeviation_nb = 2;
SM2_AVR_FrequencyDeviation_nx = 1;
SM2_AVR_FrequencyDerivative_b_2 = 0;
SM2_AVR_FrequencyDerivative_a_1 = 0.026;
SM2_AVR_FrequencyDerivative_a_2 = 1;
SM2_AVR_FrequencyDerivative_na = 2;
SM2_AVR_FrequencyDerivative_nb = 2;
SM2_AVR_FrequencyDerivative_nx = 1;
SM2_AVR_ExcitationCurrent_b_2 = 0;
SM2_AVR_ExcitationCurrent_a_1 = 0.03;
SM2_AVR_ExcitationCurrent_a_2 = 1;
SM2_AVR_ExcitationCurrent_na = 2;
SM2_AVR_ExcitationCurrent_nb = 2;
SM2_AVR_ExcitationCurrent_nx = 1;
SM2_AVR_SimpleExciter_a_2 = 1;
SM2_AVR_SimpleExciter_na = 2;
SM2_AVR_SimpleExciter_nb = 1;
SM2_AVR_SimpleExciter_nx = 1;
G1_G_DeltaIJ = 0;
BoundParameterSection
G1_AVR_VoltageDeviation_b_1 = G1_AVR_K0u;
G1_AVR_VoltageDerivative_b_1 = G1_AVR_K1u;
G1_AVR_FrequencyDeviation_b_1 = G1_AVR_K0w;
G1_AVR_FrequencyDerivative_b_1 = G1_AVR_K1w;
G1_AVR_ExcitationCurrent_b_1 = G1_AVR_K1if;
G1_AVR_SimpleExciter_a_1 = G1_AVR_Tokp;
SM2_AVR_VoltageDeviation_b_1 = SM2_AVR_K0u;
SM2_AVR_VoltageDerivative_b_1 = SM2_AVR_K1u;
SM2_AVR_FrequencyDeviation_b_1 = SM2_AVR_K0w;
SM2_AVR_FrequencyDerivative_b_1 = SM2_AVR_K1w;
SM2_AVR_ExcitationCurrent_b_1 = SM2_AVR_K1if;
SM2_AVR_SimpleExciter_a_1 = SM2_AVR_Tokp;
InitialSection
DefaultSection
InitializeData(0)

OutputSection

DynamicsSection
G1_AVR_FrequencyBlockD_y = G1_AVR_FrequencyBlockD_b_1*G1_AVR_FrequencyBlockD_x_1
;
L0102_BL = IF GreaterEqualTime(L0102_TLineOff, 0) AND LessTime(L0102_TLineOff+
L0102_dTLineOff, 1) THEN divmacro(L0102_Bline,"L0102.Bline",L0102_Koff,
"L0102.Koff") ELSE L0102_Bline;
L0102_Bnn = divmacro(L0102_BL,"L0102.BL",1+G1_G_s,"1+G1.G.s");
L0102_RL = IF GreaterEqualTime(L0102_TLineOff, 0) AND LessTime(L0102_TLineOff+
L0102_dTLineOff, 1) THEN L0102_Koff*L0102_Rline ELSE L0102_Rline;
when(initial(), 0) 
  G1_G_Xaq = G1_G_Xq-G1_G_Xs;
endwhen(0) 
when(initial(), 1) 
  G1_G_Xs1q = divmacro(1,"1",divmacro(1,"1",G1_G_X2q-G1_G_Xs,"G1.G.X2q-G1.G.Xs")
-divmacro(1,"1",G1_G_Xaq,"G1.G.Xaq"),"1/(G1.G.X2q-G1.G.Xs)-1/G1.G.Xaq");
endwhen(1) 
when(initial(), 2) 
  G1_G_X3 = divmacro(G1_G_X2q-G1_G_Xs,"G1.G.X2q-G1.G.Xs",G1_G_Xs1q,"G1.G.Xs1q");
endwhen(2) 
G1_G_E11d = G1_G_X3*G1_G_Yrq;
when(initial(), 3) 
  G1_G_Rs = 0;
endwhen(3) 
when(initial(), 4) 
  G1_G_X2qt = G1_G_X2q+G1_G_Xt;
endwhen(4) 
L0102_XL = IF GreaterEqualTime(L0102_TLineOff, 0) AND LessTime(L0102_TLineOff+
L0102_dTLineOff, 1) THEN L0102_Koff*L0102_Xline ELSE L0102_Xline;
when(initial(), 5) 
  SM2_G_Xaq = SM2_G_Xq-SM2_G_Xs;
endwhen(5) 
when(initial(), 6) 
  SM2_G_Xs1q = divmacro(1,"1",divmacro(1,"1",SM2_G_X2q-SM2_G_Xs,"SM2.G.X2q-SM2.G.Xs"
)-divmacro(1,"1",SM2_G_Xaq,"SM2.G.Xaq"),"1/(SM2.G.X2q-SM2.G.Xs)-1/SM2.G.Xaq");
endwhen(6) 
when(initial(), 7) 
  SM2_G_X3 = divmacro(SM2_G_X2q-SM2_G_Xs,"SM2.G.X2q-SM2.G.Xs",SM2_G_Xs1q,
"SM2.G.Xs1q");
endwhen(7) 
SM2_G_E11d = SM2_G_X3*SM2_G_Yrq;
when(initial(), 8) 
  SM2_G_Rs = 0;
endwhen(8) 
when(initial(), 9) 
  SM2_G_Xad = SM2_G_Xd-SM2_G_Xs;
endwhen(9) 
when(initial(), 10) 
  SM2_G_Xsf = divmacro(1,"1",divmacro(1,"1",SM2_G_X1d-SM2_G_Xs,"SM2.G.X1d-SM2.G.Xs"
)-divmacro(1,"1",SM2_G_Xad,"SM2.G.Xad"),"1/(SM2.G.X1d-SM2.G.Xs)-1/SM2.G.Xad");
endwhen(10) 
when(initial(), 11) 
  SM2_G_X1 = divmacro(SM2_G_X2d-SM2_G_Xs,"SM2.G.X2d-SM2.G.Xs",SM2_G_Xsf,
"SM2.G.Xsf");
endwhen(11) 
when(initial(), 12) 
  SM2_G_Xs1d = divmacro(1,"1",divmacro(1,"1",SM2_G_X2d-SM2_G_Xs,"SM2.G.X2d-SM2.G.Xs"
)-divmacro(1,"1",SM2_G_Xad,"SM2.G.Xad")-divmacro(1,"1",SM2_G_Xsf,"SM2.G.Xsf"),
"1/(SM2.G.X2d-SM2.G.Xs)-1/SM2.G.Xad-1/SM2.G.Xsf");
endwhen(12) 
when(initial(), 13) 
  SM2_G_X2 = divmacro(SM2_G_X2d-SM2_G_Xs,"SM2.G.X2d-SM2.G.Xs",SM2_G_Xs1d,
"SM2.G.Xs1d");
endwhen(13) 
SM2_G_E11q = SM2_G_X1*SM2_G_Yr+SM2_G_X2*SM2_G_Yrd;
when(initial(), 14) 
  SM2_G_X2qt = SM2_G_X2q+SM2_G_Xt;
endwhen(14) 
when(initial(), 15) 
  SM2_G_X2dt = SM2_G_X2d+SM2_G_Xt;
endwhen(15) 
when(initial(), 16) 
  G1_G_Xad = G1_G_Xd-G1_G_Xs;
endwhen(16) 
when(initial(), 17) 
  G1_G_Xsf = divmacro(1,"1",divmacro(1,"1",G1_G_X1d-G1_G_Xs,"G1.G.X1d-G1.G.Xs")-
divmacro(1,"1",G1_G_Xad,"G1.G.Xad"),"1/(G1.G.X1d-G1.G.Xs)-1/G1.G.Xad");
endwhen(17) 
when(initial(), 18) 
  G1_G_X1 = divmacro(G1_G_X2d-G1_G_Xs,"G1.G.X2d-G1.G.Xs",G1_G_Xsf,"G1.G.Xsf");
endwhen(18) 
when(initial(), 19) 
  G1_G_Xs1d = divmacro(1,"1",divmacro(1,"1",G1_G_X2d-G1_G_Xs,"G1.G.X2d-G1.G.Xs")
-divmacro(1,"1",G1_G_Xad,"G1.G.Xad")-divmacro(1,"1",G1_G_Xsf,"G1.G.Xsf"),
"1/(G1.G.X2d-G1.G.Xs)-1/G1.G.Xad-1/G1.G.Xsf");
endwhen(19) 
when(initial(), 20) 
  G1_G_X2 = divmacro(G1_G_X2d-G1_G_Xs,"G1.G.X2d-G1.G.Xs",G1_G_Xs1d,"G1.G.Xs1d");
endwhen(20) 
G1_G_E11q = G1_G_X1*G1_G_Yr+G1_G_X2*G1_G_Yrd;
when(initial(), 21) 
  G1_G_X2dt = G1_G_X2d+G1_G_Xt;
endwhen(21) 
BreakSectionFunction(1);



{ /* Linear system of equations to solve. */
/* Introducing 38 common subexpressions used in 72 expressions */
/* Of the common subexpressions 34 are reals, 0 are integers, and 4
 are booleans. */
/* Of the common subexpressions 28 are continuous, 10 are discrete, and 0
 are parameter expressions */
double helpvar[38];
helpvar[0] = GreaterEqualTime(SM2_G_TgenOff, 2) AND LessTime(SM2_G_TgenOff+
SM2_G_dTgenOff, 3);
helpvar[1] = IF helpvar[0] THEN 0 ELSE  -divmacro(SM2_G_Rs,"SM2.G.Rs",SM2_G_X2qt
,"SM2.G.X2qt");
helpvar[2] = cos(delta__G1__SM2);
helpvar[3] = GreaterEqualTime(G1_G_TgenOff, 4) AND LessTime(G1_G_TgenOff+
G1_G_dTgenOff, 5);
helpvar[4] = IF helpvar[3] THEN 0 ELSE divmacro(G1_G_X2qt,"G1.G.X2qt",G1_G_X2dt*
G1_G_X2qt+powmacro(G1_G_Rs,"G1.G.Rs",2,"2"),"G1.G.X2dt*G1.G.X2qt+G1.G.Rs^2");
helpvar[5] = IF helpvar[3] THEN 0 ELSE  -divmacro(G1_G_Rs,"G1.G.Rs",G1_G_X2qt,
"G1.G.X2qt");
helpvar[6] = helpvar[4]*helpvar[5];
helpvar[7] = GreaterEqualTime(KZ1_TkzOn, 6) AND LessTime(KZ1_TkzOn+KZ1_dTkzOn, 7
);
helpvar[8] = IF helpvar[3] THEN 0 ELSE  -divmacro(G1_G_Rs,"G1.G.Rs",G1_G_X2dt*
G1_G_X2qt+powmacro(G1_G_Rs,"G1.G.Rs",2,"2"),"G1.G.X2dt*G1.G.X2qt+G1.G.Rs^2");
helpvar[9] = (-0.5)*L0102_Bnn;
helpvar[10] = (-1)*(IF helpvar[7] THEN  -KZ1_Bn ELSE 0)+helpvar[8]*helpvar[5]+(
IF helpvar[3] THEN 0 ELSE  -divmacro(1,"1",G1_G_X2qt,"G1.G.X2qt"))-helpvar[9];
helpvar[11] = L0102_RL*helpvar[6]+L0102_XL*helpvar[10];
helpvar[12] = 1+(-1)*helpvar[11];
helpvar[13] = sin(delta__G1__SM2);
helpvar[14] = L0102_RL*helpvar[10]-L0102_XL*helpvar[6];
helpvar[15] = helpvar[2]*helpvar[12]-(-1)*helpvar[13]*helpvar[14];
helpvar[16] = helpvar[1]*helpvar[15]+helpvar[13]*helpvar[12]+(-1)*helpvar[2]*
helpvar[14];
helpvar[17] = IF helpvar[0] THEN 0 ELSE  -divmacro(SM2_G_E11q*SM2_G_X2qt+
SM2_G_Rs*SM2_G_E11d,"SM2.G.E11q*SM2.G.X2qt+SM2.G.Rs*SM2.G.E11d",SM2_G_X2dt*
SM2_G_X2qt+powmacro(SM2_G_Rs,"SM2.G.Rs",2,"2"),"SM2.G.X2dt*SM2.G.X2qt+SM2.G.Rs^2"
);
helpvar[18] = IF helpvar[0] THEN 0 ELSE  -divmacro(SM2_G_E11d,"SM2.G.E11d",
SM2_G_X2qt,"SM2.G.X2qt");
helpvar[19] = IF helpvar[3] THEN 0 ELSE  -divmacro(G1_G_E11q*G1_G_X2qt+G1_G_Rs*
G1_G_E11d,"G1.G.E11q*G1.G.X2qt+G1.G.Rs*G1.G.E11d",G1_G_X2dt*G1_G_X2qt+powmacro(
G1_G_Rs,"G1.G.Rs",2,"2"),"G1.G.X2dt*G1.G.X2qt+G1.G.Rs^2");
helpvar[20] = (-1)*(IF helpvar[7] THEN KZ1_Bn ELSE 0)+helpvar[4]+helpvar[9];
helpvar[21] = L0102_RL*helpvar[20]+L0102_XL*helpvar[8];
helpvar[22] = L0102_RL*helpvar[8]-L0102_XL*helpvar[20];
helpvar[23] = 1+(-1)*helpvar[22];
helpvar[24] = (-1)*helpvar[2]*helpvar[21]-helpvar[13]*helpvar[23];
helpvar[25] = helpvar[1]*helpvar[24]+(-1)*helpvar[13]*helpvar[21]+helpvar[2]*
helpvar[23];
/* Automatic tearing of linear system of 26 simultaneous equations
gave a linear system of 2 equations for numerical solution.*/
{
  StaticLinearSystemOfEquations(J, b, y, 2);
  /* Jacobian depending on continuous variables */
  SetNeedFactor(J);
  if (NeedFactor(J)) {
    MatrixZeros(J);
    helpvar[26] = IF helpvar[0] THEN 0 ELSE  -divmacro(SM2_G_Rs,"SM2.G.Rs",
    SM2_G_X2dt*SM2_G_X2qt+powmacro(SM2_G_Rs,"SM2.G.Rs",2,"2"),"SM2.G.X2dt*SM2.G.X2qt+SM2.G.Rs^2"
    );
    helpvar[27] = IF helpvar[0] THEN 0 ELSE  -divmacro(1,"1",SM2_G_X2qt,
    "SM2.G.X2qt");
    helpvar[28] = helpvar[26]*helpvar[16]+helpvar[27]*helpvar[15];
    helpvar[29] = (-1)+helpvar[11];
    helpvar[30] = IF helpvar[0] THEN 0 ELSE divmacro(SM2_G_X2qt,"SM2.G.X2qt",
    SM2_G_X2dt*SM2_G_X2qt+powmacro(SM2_G_Rs,"SM2.G.Rs",2,"2"),"SM2.G.X2dt*SM2.G.X2qt+SM2.G.Rs^2"
    );
    helpvar[31] = helpvar[30]*helpvar[16];
    helpvar[32] = GreaterEqualTime(KZ2_TkzOn, 8) AND LessTime(KZ2_TkzOn+
    KZ2_dTkzOn, 9);
    helpvar[33] = IF helpvar[32] THEN  -KZ2_Bn ELSE 0;
    helpvar[34] = IF helpvar[32] THEN KZ2_Bn ELSE 0;
    helpvar[35] = helpvar[26]*helpvar[25]+helpvar[27]*helpvar[24];
    helpvar[36] = helpvar[30]*helpvar[25];
    helpvar[37] = (-1)+helpvar[22];
    SetMatrix(J, 1, 1, helpvar[28]*helpvar[2]-0.5*helpvar[29]*L0102_Bnn-helpvar[
    31]*helpvar[13]+helpvar[29]*helpvar[33]+helpvar[10]);
    SetMatrix(J, 1, 2, helpvar[28]*helpvar[13]+helpvar[31]*helpvar[2]+0.5*
    helpvar[14]*L0102_Bnn+helpvar[14]*helpvar[34]+helpvar[6]);
    SetMatrix(J, 2, 1, helpvar[35]*helpvar[2]-0.5*helpvar[21]*L0102_Bnn-helpvar[
    36]*helpvar[13]+helpvar[21]*helpvar[33]+helpvar[8]);
    SetMatrix(J, 2, 2, helpvar[35]*helpvar[13]+helpvar[36]*helpvar[2]+0.5*
    helpvar[37]*L0102_Bnn+helpvar[37]*helpvar[34]+helpvar[20]);
  }
  SetVector(b, 1,  -(helpvar[16]*helpvar[17]+helpvar[15]*helpvar[18]+helpvar[5]*
  helpvar[19]+(IF helpvar[3] THEN 0 ELSE  -divmacro(G1_G_E11d,"G1.G.E11d",
  G1_G_X2qt,"G1.G.X2qt"))));
  SetVector(b, 2,  -(helpvar[25]*helpvar[17]+helpvar[24]*helpvar[18]+helpvar[19]
  ));
  SetVector(y, 1, Remember_(L0102_U2d, 0));
  SetVector(y, 2, Remember_(L0102_U2q, 1));
  SolveLinearSystemOfEquations(J, b, y, 1);
  L0102_U2d = GetVector(y, 1);
  L0102_U2q = GetVector(y, 2);
  EndStaticLinearSystemOfEquations(J);
}
L0102_Iqc2 =  -0.5*L0102_U2d*L0102_Bnn;
SM2_G_ud = L0102_U2q*sin(delta__G1__SM2)+L0102_U2d*cos(delta__G1__SM2);
SM2_G_uq = L0102_U2q*cos(delta__G1__SM2)-L0102_U2d*sin(delta__G1__SM2);
SM2_G_id = IF GreaterEqualTime(SM2_G_TgenOff, 2) AND LessTime(SM2_G_TgenOff+
SM2_G_dTgenOff, 3) THEN 0 ELSE divmacro((SM2_G_uq-SM2_G_E11q)*SM2_G_X2qt-
SM2_G_Rs*(SM2_G_ud+SM2_G_E11d),"(SM2.G.uq-SM2.G.E11q)*SM2.G.X2qt-SM2.G.Rs*(SM2.G.ud+SM2.G.E11d)"
,SM2_G_X2dt*SM2_G_X2qt+powmacro(SM2_G_Rs,"SM2.G.Rs",2,"2"),"SM2.G.X2dt*SM2.G.X2qt+SM2.G.Rs^2"
);
SM2_G_iq = IF GreaterEqualTime(SM2_G_TgenOff, 2) AND LessTime(SM2_G_TgenOff+
SM2_G_dTgenOff, 3) THEN 0 ELSE  -divmacro(SM2_G_ud+SM2_G_E11d+SM2_G_Rs*SM2_G_id,
"SM2.G.ud+SM2.G.E11d+SM2.G.Rs*SM2.G.id",SM2_G_X2qt,"SM2.G.X2qt");
SM2_G_IqG = SM2_G_iq*cos(delta__G1__SM2)+SM2_G_id*sin(delta__G1__SM2);
KZ2_iq = IF GreaterEqualTime(KZ2_TkzOn, 8) AND LessTime(KZ2_TkzOn+KZ2_dTkzOn, 9)
 THEN  -KZ2_Bn*L0102_U2d ELSE 0;
L0102_I2q = KZ2_iq-SM2_G_IqG;
L0102_I12q = L0102_Iqc2+L0102_I2q;
L0102_Idc2 = 0.5*L0102_U2q*L0102_Bnn;
SM2_G_IdG = SM2_G_id*cos(delta__G1__SM2)-SM2_G_iq*sin(delta__G1__SM2);
KZ2_id = IF GreaterEqualTime(KZ2_TkzOn, 8) AND LessTime(KZ2_TkzOn+KZ2_dTkzOn, 9)
 THEN KZ2_Bn*L0102_U2q ELSE 0;
L0102_I2d = KZ2_id-SM2_G_IdG;
L0102_I12d = L0102_Idc2+L0102_I2d;
L0102_U1q = L0102_U2q+L0102_RL*L0102_I12q-L0102_XL*L0102_I12d;
KZ1_id = IF GreaterEqualTime(KZ1_TkzOn, 6) AND LessTime(KZ1_TkzOn+KZ1_dTkzOn, 7)
 THEN KZ1_Bn*L0102_U1q ELSE 0;
L0102_U1d = L0102_U2d+L0102_RL*L0102_I12d+L0102_XL*L0102_I12q;
KZ1_iq = IF GreaterEqualTime(KZ1_TkzOn, 6) AND LessTime(KZ1_TkzOn+KZ1_dTkzOn, 7)
 THEN  -KZ1_Bn*L0102_U1d ELSE 0;
G1_G_id = IF GreaterEqualTime(G1_G_TgenOff, 4) AND LessTime(G1_G_TgenOff+
G1_G_dTgenOff, 5) THEN 0 ELSE divmacro((L0102_U1q-G1_G_E11q)*G1_G_X2qt-G1_G_Rs*(
L0102_U1d+G1_G_E11d),"(L0102.U1q-G1.G.E11q)*G1.G.X2qt-G1.G.Rs*(L0102.U1d+G1.G.E11d)"
,G1_G_X2dt*G1_G_X2qt+powmacro(G1_G_Rs,"G1.G.Rs",2,"2"),"G1.G.X2dt*G1.G.X2qt+G1.G.Rs^2"
);
G1_G_iq = IF GreaterEqualTime(G1_G_TgenOff, 4) AND LessTime(G1_G_TgenOff+
G1_G_dTgenOff, 5) THEN 0 ELSE  -divmacro(L0102_U1d+G1_G_E11d+G1_G_Rs*G1_G_id,
"L0102.U1d+G1.G.E11d+G1.G.Rs*G1.G.id",G1_G_X2qt,"G1.G.X2qt");
L0102_Iqc1 =  -0.5*L0102_U1d*L0102_Bnn;
L0102_I1q = L0102_Iqc1+L0102_I12q;
L0102_Idc1 = 0.5*L0102_U1q*L0102_Bnn;
L0102_I1d = L0102_Idc1+L0102_I12d;
 /* End of Equation Block */ }

BreakSectionFunction(2);
G1_AVR_FrequencyBlockU_u = IF NotEqual(L0102_U1q, 0, 0) THEN atan2(L0102_U1d, 
L0102_U1q) ELSE atan2(L0102_U1d, 0.001);
G1_AVR_FrequencyBlockU_der_x_1 = (-14.2857142857143)*(G1_AVR_FrequencyBlockU_x_1
-G1_AVR_FrequencyBlockU_u);
G1_AVR_FrequencyBlockU_y = G1_AVR_FrequencyBlockU_b_1*G1_AVR_FrequencyBlockU_der_x_1
+G1_AVR_FrequencyBlockU_b_2*G1_AVR_FrequencyBlockU_x_1;
G1_AVR_FrequencyDeviation_u = G1_AVR_FrequencyBlockD_y+G1_AVR_FrequencyBlockU_y;
G1_AVR_FrequencyDerivative_der_x_1 = (-38.4615384615385)*(G1_AVR_FrequencyDerivative_x_1
-G1_AVR_FrequencyDeviation_u);
G1_AVR_FrequencyBlockD_u = 314.159265358979*G1_G_s;
G1_AVR_FrequencyBlockD_der_x_1 = (-14.2857142857143)*(G1_AVR_FrequencyBlockD_x_1
-G1_AVR_FrequencyBlockD_u);
G1_AVR_FrequencyDeviation_der_x_1 = G1_AVR_FrequencyDeviation_u-G1_AVR_FrequencyDeviation_x_1
;
G1_AVR_VoltageDeviation_u = sqrt(powmacro(L0102_U1d,"L0102.U1d",2,"2")+powmacro(
L0102_U1q,"L0102.U1q",2,"2"))-G1_G_Ut;
G1_AVR_VoltageDerivative_der_x_1 = (-25.6410256410256)*(G1_AVR_VoltageDerivative_x_1
-G1_AVR_VoltageDeviation_u);
G1_G_Yaq = G1_G_E11d+G1_G_iq*(G1_G_X2q-G1_G_Xs);
G1_G_irq = divmacro(G1_G_Yrq-G1_G_Yaq,"G1.G.Yrq-G1.G.Yaq",G1_G_Xs1q,"G1.G.Xs1q")
;
G1_G_der_Yrq =  -314.159265358979*G1_G_R1q*G1_G_irq;
SM2_G_Yaq = SM2_G_E11d+SM2_G_iq*(SM2_G_X2q-SM2_G_Xs);
SM2_G_irq = divmacro(SM2_G_Yrq-SM2_G_Yaq,"SM2.G.Yrq-SM2.G.Yaq",SM2_G_Xs1q,
"SM2.G.Xs1q");
SM2_G_der_Yrq =  -314.159265358979*SM2_G_R1q*SM2_G_irq;
SM2_G_Yad = SM2_G_E11q+SM2_G_id*(SM2_G_X2d-SM2_G_Xs);
SM2_G_ird = divmacro(SM2_G_Yrd-SM2_G_Yad,"SM2.G.Yrd-SM2.G.Yad",SM2_G_Xs1d,
"SM2.G.Xs1d");
SM2_G_der_Yrd =  -314.159265358979*SM2_G_R1d*SM2_G_ird;
SM2_AVR_VoltageDeviation_y = SM2_AVR_VoltageDeviation_b_1*SM2_AVR_VoltageDeviation_x_1
;
SM2_AVR_VoltageDeviation_u = sqrt(powmacro(SM2_G_ud,"SM2.G.ud",2,"2")+powmacro(
SM2_G_uq,"SM2.G.uq",2,"2"))-SM2_G_Ut;
SM2_AVR_VoltageDerivative_der_x_1 = (-25.6410256410256)*(SM2_AVR_VoltageDerivative_x_1
-SM2_AVR_VoltageDeviation_u);
SM2_AVR_VoltageDerivative_y = SM2_AVR_VoltageDerivative_b_1*SM2_AVR_VoltageDerivative_der_x_1
;
SM2_G_ir = divmacro(SM2_G_Yr-SM2_G_Yad,"SM2.G.Yr-SM2.G.Yad",SM2_G_Xsf,
"SM2.G.Xsf");
when(initial(), 22) 
  SM2_G_Dg = atan2(divmacro((SM2_G_Xq+SM2_G_Xt)*SM2_G_Pg,"(SM2.G.Xq+SM2.G.Xt)*SM2.G.Pg"
,SM2_G_Ut,"SM2.G.Ut"), SM2_G_Ut+divmacro((SM2_G_Xq+SM2_G_Xt)*SM2_G_Qg,
"(SM2.G.Xq+SM2.G.Xt)*SM2.G.Qg",SM2_G_Ut,"SM2.G.Ut"));
endwhen(22) 
when(initial(), 23) 
  SM2_G_Uq = SM2_G_Ut*cos(SM2_G_Dg);
endwhen(23) 
when(initial(), 24) 
  SM2_G_EQ = sqrt(powmacro(SM2_G_Ut+divmacro((SM2_G_Xq+SM2_G_Xt)*SM2_G_Qg,
"(SM2.G.Xq+SM2.G.Xt)*SM2.G.Qg",SM2_G_Ut,"SM2.G.Ut"),"SM2.G.Ut+(SM2.G.Xq+SM2.G.Xt)*SM2.G.Qg/SM2.G.Ut"
,2,"2")+powmacro(divmacro((SM2_G_Xq+SM2_G_Xt)*SM2_G_Pg,"(SM2.G.Xq+SM2.G.Xt)*SM2.G.Pg"
,SM2_G_Ut,"SM2.G.Ut"),"(SM2.G.Xq+SM2.G.Xt)*SM2.G.Pg/SM2.G.Ut",2,"2"));
endwhen(24) 
when(initial(), 25) 
  SM2_G_Id = divmacro((SM2_G_Uq-SM2_G_EQ)*(SM2_G_Xq+SM2_G_Xt),"(SM2.G.Uq-SM2.G.EQ)*(SM2.G.Xq+SM2.G.Xt)"
,powmacro(SM2_G_Xq+SM2_G_Xt,"SM2.G.Xq+SM2.G.Xt",2,"2"),"(SM2.G.Xq+SM2.G.Xt)^2");
endwhen(25) 
when(initial(), 26) 
  SM2_G_Eiq = SM2_G_Uq-SM2_G_Id*(SM2_G_Xs+SM2_G_Xt);
endwhen(26) 
when(initial(), 27) 
  SM2_G_Ir = divmacro(SM2_G_Eiq,"SM2.G.Eiq",SM2_G_Xad,"SM2.G.Xad")-SM2_G_Id;
endwhen(27) 
SM2_AVR_ExcitationCurrent_u = SM2_G_ir-SM2_G_Ir;
SM2_AVR_ExcitationCurrent_der_x_1 = (-33.3333333333333)*(SM2_AVR_ExcitationCurrent_x_1
-SM2_AVR_ExcitationCurrent_u);
SM2_AVR_ExcitationCurrent_y = SM2_AVR_ExcitationCurrent_b_1*SM2_AVR_ExcitationCurrent_der_x_1
;
SM2_AVR_FrequencyBlockD_y = SM2_AVR_FrequencyBlockD_b_1*SM2_AVR_FrequencyBlockD_x_1
;
SM2_AVR_FrequencyBlockU_u = IF NotEqual(L0102_U2q, 0, 1) THEN atan2(L0102_U2d, 
L0102_U2q) ELSE atan2(L0102_U2d, 0.001);
SM2_AVR_FrequencyBlockU_der_x_1 = (-14.2857142857143)*(SM2_AVR_FrequencyBlockU_x_1
-SM2_AVR_FrequencyBlockU_u);
SM2_AVR_FrequencyBlockU_y = SM2_AVR_FrequencyBlockU_b_1*SM2_AVR_FrequencyBlockU_der_x_1
+SM2_AVR_FrequencyBlockU_b_2*SM2_AVR_FrequencyBlockU_x_1;
SM2_AVR_FrequencyDeviation_u = SM2_AVR_FrequencyBlockD_y+SM2_AVR_FrequencyBlockU_y
;
SM2_AVR_FrequencyDeviation_der_x_1 = SM2_AVR_FrequencyDeviation_u-
SM2_AVR_FrequencyDeviation_x_1;
SM2_AVR_FrequencyDeviation_y = SM2_AVR_FrequencyDeviation_b_1*SM2_AVR_FrequencyDeviation_der_x_1
;
SM2_AVR_FrequencyDerivative_der_x_1 = (-38.4615384615385)*(SM2_AVR_FrequencyDerivative_x_1
-SM2_AVR_FrequencyDeviation_u);
SM2_AVR_FrequencyDerivative_y = SM2_AVR_FrequencyDerivative_b_1*SM2_AVR_FrequencyDerivative_der_x_1
;
SM2_AVR_SimpleExciter_u = SM2_AVR_VoltageDeviation_y+SM2_AVR_VoltageDerivative_y
+SM2_AVR_ExcitationCurrent_y+SM2_AVR_FrequencyDeviation_y+SM2_AVR_FrequencyDerivative_y
;
SM2_AVR_SimpleExciter_der_x_1 =  -divmacro(SM2_AVR_SimpleExciter_x_1-
SM2_AVR_SimpleExciter_u,"SM2.AVR.SimpleExciter.x[1]-SM2.AVR.SimpleExciter.u",
SM2_AVR_SimpleExciter_a_1,"SM2.AVR.SimpleExciter.a[1]");
SM2_AVR_FrequencyBlockD_u = 314.159265358979*G1_G_s;
SM2_AVR_FrequencyBlockD_der_x_1 = (-14.2857142857143)*(SM2_AVR_FrequencyBlockD_x_1
-SM2_AVR_FrequencyBlockD_u);
SM2_AVR_VoltageDeviation_der_x_1 = (-50.0)*(SM2_AVR_VoltageDeviation_x_1-
SM2_AVR_VoltageDeviation_u);
when(initial(), 28) 
  SM2_G_Uf = SM2_G_Ir*SM2_G_Rf;
endwhen(28) 
SM2_G_dEr = SM2_AVR_SimpleExciter_b_1*SM2_AVR_SimpleExciter_x_1;
when(initial(), 29) 
  SM2_G_Eq = SM2_G_Ir*SM2_G_Xad;
endwhen(29) 
when(initial(), 30) 
  SM2_G_Er0 = SM2_G_Eq;
endwhen(30) 
when(initial(), 31) 
  SM2_G_Er__max = 2*SM2_G_Er0;
endwhen(31) 
when(initial(), 32) 
  SM2_G_Er__min =  -0.6*SM2_G_Er0;
endwhen(32) 
SM2_G_Uf__full = IF Greater(divmacro(SM2_G_Uf*SM2_G_Xad,"SM2.G.Uf*SM2.G.Xad",
SM2_G_Rf,"SM2.G.Rf")+SM2_G_dEr,"SM2.G.Uf*SM2.G.Xad/SM2.G.Rf+SM2.G.dEr", 
SM2_G_Er__max,"SM2.G.Er_max", 2) THEN divmacro(SM2_G_Er__max*SM2_G_Rf,
"SM2.G.Er_max*SM2.G.Rf",SM2_G_Xad,"SM2.G.Xad") ELSE IF Less(divmacro(SM2_G_Uf*
SM2_G_Xad,"SM2.G.Uf*SM2.G.Xad",SM2_G_Rf,"SM2.G.Rf")+SM2_G_dEr,"SM2.G.Uf*SM2.G.Xad/SM2.G.Rf+SM2.G.dEr"
, SM2_G_Er__min,"SM2.G.Er_min", 3) THEN divmacro(SM2_G_Er__min*SM2_G_Rf,
"SM2.G.Er_min*SM2.G.Rf",SM2_G_Xad,"SM2.G.Xad") ELSE SM2_G_Uf+divmacro(SM2_G_Rf*
SM2_G_dEr,"SM2.G.Rf*SM2.G.dEr",SM2_G_Xad,"SM2.G.Xad");
SM2_G_der_Yr = 314.159265358979*(SM2_G_Uf__full-SM2_G_Rf*SM2_G_ir);
when(initial(), 33) 
  SM2_G_Ud =  -SM2_G_Ut*sin(SM2_G_Dg);
endwhen(33) 
when(initial(), 34) 
  SM2_G_Iq =  -divmacro(SM2_G_Ud,"SM2.G.Ud",SM2_G_Xq+SM2_G_Xt,"SM2.G.Xq+SM2.G.Xt"
);
endwhen(34) 
when(initial(), 35) 
  SM2_G_Mt = SM2_G_EQ*SM2_G_Iq;
endwhen(35) 
when(initial(), 36) 
  SM2_G_Mu0 = SM2_G_Mt;
endwhen(36) 
SM2_G_Ro = SM2_G_Mu0-SM2_G_Mu-divmacro(SM2_G_s,"SM2.G.s",SM2_G_Sigma,
"SM2.G.Sigma");
SM2_G_der_Mu = divmacro(SM2_G_Ro,"SM2.G.Ro",SM2_G_TauC,"SM2.G.TauC");
SM2_G_Mt__pp = IF GreaterEqual(SM2_G_Mu,"SM2.G.Mu", SM2_G_Mt__min,"SM2.G.Mt_min"
, 4) AND LessEqual(SM2_G_Mu,"SM2.G.Mu", SM2_G_Mt__max,"SM2.G.Mt_max", 5) THEN 
SM2_G_Mu ELSE IF Greater(SM2_G_Mu,"SM2.G.Mu", SM2_G_Mt__max,"SM2.G.Mt_max", 6)
 THEN SM2_G_Mt__max ELSE SM2_G_Mt__min;
SM2_G_Me = SM2_G_Yad*SM2_G_iq-SM2_G_Yaq*SM2_G_id;
SM2_G_der_s = divmacro(SM2_G_Mt__pp-SM2_G_Me,"SM2.G.Mt_pp-SM2.G.Me",SM2_G_Tj,
"SM2.G.Tj");
der_delta__G1__SM2 = 314.159265358979*(G1_G_s-SM2_G_s);
G1_G_Yad = G1_G_E11q+G1_G_id*(G1_G_X2d-G1_G_Xs);
G1_G_ird = divmacro(G1_G_Yrd-G1_G_Yad,"G1.G.Yrd-G1.G.Yad",G1_G_Xs1d,"G1.G.Xs1d")
;
G1_G_der_Yrd =  -314.159265358979*G1_G_R1d*G1_G_ird;
when(initial(), 37) 
  G1_G_EQ = sqrt(powmacro(G1_G_Ut+divmacro((G1_G_Xq+G1_G_Xt)*G1_G_Qg,
"(G1.G.Xq+G1.G.Xt)*G1.G.Qg",G1_G_Ut,"G1.G.Ut"),"G1.G.Ut+(G1.G.Xq+G1.G.Xt)*G1.G.Qg/G1.G.Ut"
,2,"2")+powmacro(divmacro((G1_G_Xq+G1_G_Xt)*G1_G_Pg,"(G1.G.Xq+G1.G.Xt)*G1.G.Pg",
G1_G_Ut,"G1.G.Ut"),"(G1.G.Xq+G1.G.Xt)*G1.G.Pg/G1.G.Ut",2,"2"));
endwhen(37) 
when(initial(), 38) 
  G1_G_Dg = atan2(divmacro((G1_G_Xq+G1_G_Xt)*G1_G_Pg,"(G1.G.Xq+G1.G.Xt)*G1.G.Pg"
,G1_G_Ut,"G1.G.Ut"), G1_G_Ut+divmacro((G1_G_Xq+G1_G_Xt)*G1_G_Qg,"(G1.G.Xq+G1.G.Xt)*G1.G.Qg"
,G1_G_Ut,"G1.G.Ut"));
endwhen(38) 
when(initial(), 39) 
  G1_G_Ud =  -G1_G_Ut*sin(G1_G_Dg);
endwhen(39) 
when(initial(), 40) 
  G1_G_Iq =  -divmacro(G1_G_Ud,"G1.G.Ud",G1_G_Xq+G1_G_Xt,"G1.G.Xq+G1.G.Xt");
endwhen(40) 
when(initial(), 41) 
  G1_G_Mt = G1_G_EQ*G1_G_Iq;
endwhen(41) 
when(initial(), 42) 
  G1_G_Mu0 = G1_G_Mt;
endwhen(42) 
G1_G_Ro = G1_G_Mu0-G1_G_Mu-divmacro(G1_G_s,"G1.G.s",G1_G_Sigma,"G1.G.Sigma");
G1_G_der_Mu = divmacro(G1_G_Ro,"G1.G.Ro",G1_G_TauC,"G1.G.TauC");
G1_G_Mt__pp = IF GreaterEqual(G1_G_Mu,"G1.G.Mu", G1_G_Mt__min,"G1.G.Mt_min", 7)
 AND LessEqual(G1_G_Mu,"G1.G.Mu", G1_G_Mt__max,"G1.G.Mt_max", 8) THEN G1_G_Mu
 ELSE IF Greater(G1_G_Mu,"G1.G.Mu", G1_G_Mt__max,"G1.G.Mt_max", 9) THEN 
G1_G_Mt__max ELSE G1_G_Mt__min;
G1_G_Me = G1_G_Yad*G1_G_iq-G1_G_Yaq*G1_G_id;
G1_G_der_s = divmacro(G1_G_Mt__pp-G1_G_Me,"G1.G.Mt_pp-G1.G.Me",G1_G_Tj,"G1.G.Tj"
);
G1_AVR_VoltageDeviation_der_x_1 = (-50.0)*(G1_AVR_VoltageDeviation_x_1-
G1_AVR_VoltageDeviation_u);
G1_G_ir = divmacro(G1_G_Yr-G1_G_Yad,"G1.G.Yr-G1.G.Yad",G1_G_Xsf,"G1.G.Xsf");
when(initial(), 43) 
  G1_G_Uq = G1_G_Ut*cos(G1_G_Dg);
endwhen(43) 
when(initial(), 44) 
  G1_G_Id = divmacro((G1_G_Uq-G1_G_EQ)*(G1_G_Xq+G1_G_Xt),"(G1.G.Uq-G1.G.EQ)*(G1.G.Xq+G1.G.Xt)"
,powmacro(G1_G_Xq+G1_G_Xt,"G1.G.Xq+G1.G.Xt",2,"2"),"(G1.G.Xq+G1.G.Xt)^2");
endwhen(44) 
when(initial(), 45) 
  G1_G_Eiq = G1_G_Uq-G1_G_Id*(G1_G_Xs+G1_G_Xt);
endwhen(45) 
when(initial(), 46) 
  G1_G_Ir = divmacro(G1_G_Eiq,"G1.G.Eiq",G1_G_Xad,"G1.G.Xad")-G1_G_Id;
endwhen(46) 
G1_AVR_ExcitationCurrent_u = G1_G_ir-G1_G_Ir;
G1_AVR_ExcitationCurrent_der_x_1 = (-33.3333333333333)*(G1_AVR_ExcitationCurrent_x_1
-G1_AVR_ExcitationCurrent_u);
when(initial(), 47) 
  G1_G_Uf = G1_G_Ir*G1_G_Rf;
endwhen(47) 
G1_G_dEr = G1_AVR_SimpleExciter_b_1*G1_AVR_SimpleExciter_x_1;
when(initial(), 48) 
  G1_G_Eq = G1_G_Ir*G1_G_Xad;
endwhen(48) 
when(initial(), 49) 
  G1_G_Er0 = G1_G_Eq;
endwhen(49) 
when(initial(), 50) 
  G1_G_Er__max = 2*G1_G_Er0;
endwhen(50) 
when(initial(), 51) 
  G1_G_Er__min =  -0.6*G1_G_Er0;
endwhen(51) 
G1_G_Uf__full = IF Greater(divmacro(G1_G_Uf*G1_G_Xad,"G1.G.Uf*G1.G.Xad",G1_G_Rf,
"G1.G.Rf")+G1_G_dEr,"G1.G.Uf*G1.G.Xad/G1.G.Rf+G1.G.dEr", G1_G_Er__max,
"G1.G.Er_max", 10) THEN divmacro(G1_G_Er__max*G1_G_Rf,"G1.G.Er_max*G1.G.Rf",
G1_G_Xad,"G1.G.Xad") ELSE IF Less(divmacro(G1_G_Uf*G1_G_Xad,"G1.G.Uf*G1.G.Xad",
G1_G_Rf,"G1.G.Rf")+G1_G_dEr,"G1.G.Uf*G1.G.Xad/G1.G.Rf+G1.G.dEr", G1_G_Er__min,
"G1.G.Er_min", 11) THEN divmacro(G1_G_Er__min*G1_G_Rf,"G1.G.Er_min*G1.G.Rf",
G1_G_Xad,"G1.G.Xad") ELSE G1_G_Uf+divmacro(G1_G_Rf*G1_G_dEr,"G1.G.Rf*G1.G.dEr",
G1_G_Xad,"G1.G.Xad");
G1_G_der_Yr = 314.159265358979*(G1_G_Uf__full-G1_G_Rf*G1_G_ir);
G1_AVR_VoltageDeviation_y = G1_AVR_VoltageDeviation_b_1*G1_AVR_VoltageDeviation_x_1
;
G1_AVR_VoltageDerivative_y = G1_AVR_VoltageDerivative_b_1*G1_AVR_VoltageDerivative_der_x_1
;
G1_AVR_ExcitationCurrent_y = G1_AVR_ExcitationCurrent_b_1*G1_AVR_ExcitationCurrent_der_x_1
;
G1_AVR_FrequencyDeviation_y = G1_AVR_FrequencyDeviation_b_1*G1_AVR_FrequencyDeviation_der_x_1
;
G1_AVR_FrequencyDerivative_y = G1_AVR_FrequencyDerivative_b_1*G1_AVR_FrequencyDerivative_der_x_1
;
G1_AVR_SimpleExciter_u = G1_AVR_VoltageDeviation_y+G1_AVR_VoltageDerivative_y+
G1_AVR_ExcitationCurrent_y+G1_AVR_FrequencyDeviation_y+G1_AVR_FrequencyDerivative_y
;
G1_AVR_SimpleExciter_der_x_1 =  -divmacro(G1_AVR_SimpleExciter_x_1-
G1_AVR_SimpleExciter_u,"G1.AVR.SimpleExciter.x[1]-G1.AVR.SimpleExciter.u",
G1_AVR_SimpleExciter_a_1,"G1.AVR.SimpleExciter.a[1]");

AcceptedSection
when(initial(), 52) 
  G1_G_PsiR = G1_G_Eiq+G1_G_Xsf*G1_G_Ir;
endwhen(52) 
when(initial(), 53) 
  G1_G_PsiRD = G1_G_Eiq;
endwhen(53) 
when(initial(), 54) 
  G1_G_PsiRQ =  -(G1_G_Ud+G1_G_Iq*(G1_G_Xs+G1_G_Xt));
endwhen(54) 
G1_G_Ugen = sqrt(powmacro(L0102_U1d,"L0102.U1d",2,"2")+powmacro(L0102_U1q,
"L0102.U1q",2,"2"));
G1_G_Pgen = L0102_U1q*G1_G_iq+L0102_U1d*G1_G_id;
G1_G_Qgen = L0102_U1d*G1_G_iq-L0102_U1q*G1_G_id;
L0102_I12m = sqrt(powmacro(L0102_I12d,"L0102.I12d",2,"2")+powmacro(L0102_I12q,
"L0102.I12q",2,"2"));
L0102_U1m = sqrt(powmacro(L0102_U1d,"L0102.U1d",2,"2")+powmacro(L0102_U1q,
"L0102.U1q",2,"2"));
L0102_U2m = sqrt(powmacro(L0102_U2d,"L0102.U2d",2,"2")+powmacro(L0102_U2q,
"L0102.U2q",2,"2"));
L0102_DU1 = atan2(L0102_U1d, L0102_U1q);
L0102_DU2 = atan2(L0102_U2d, L0102_U2q);
L0102_P1 = L0102_U1q*L0102_I1q+L0102_U1d*L0102_I1d;
L0102_Q1 = L0102_U1d*L0102_I1q-L0102_U1q*L0102_I1d;
L0102_P2 = L0102_U2q*L0102_I2q+L0102_U2d*L0102_I2d;
L0102_Q2 = L0102_U2d*L0102_I2q-L0102_U2q*L0102_I2d;
when(initial(), 55) 
  SM2_G_PsiR = SM2_G_Eiq+SM2_G_Xsf*SM2_G_Ir;
endwhen(55) 
when(initial(), 56) 
  SM2_G_PsiRD = SM2_G_Eiq;
endwhen(56) 
when(initial(), 57) 
  SM2_G_PsiRQ =  -(SM2_G_Ud+SM2_G_Iq*(SM2_G_Xs+SM2_G_Xt));
endwhen(57) 
SM2_G_Ugen = sqrt(powmacro(SM2_G_ud,"SM2.G.ud",2,"2")+powmacro(SM2_G_uq,
"SM2.G.uq",2,"2"));
SM2_G_Pgen = SM2_G_uq*SM2_G_iq+SM2_G_ud*SM2_G_id;
SM2_G_Qgen = SM2_G_ud*SM2_G_iq-SM2_G_uq*SM2_G_id;

DefaultSection
when(initial(), 58) 
  reinit(G1_G_s, 0);
endwhen(58) 
when(initial(), 59) 
  reinit(G1_G_Yr, G1_G_PsiR);
endwhen(59) 
when(initial(), 60) 
  reinit(G1_G_Yrd, G1_G_PsiRD);
endwhen(60) 
when(initial(), 61) 
  reinit(G1_G_Yrq, G1_G_PsiRQ);
endwhen(61) 
when(initial(), 62) 
  reinit(G1_G_Mu, G1_G_Mu0);
endwhen(62) 
when(initial(), 63) 
  reinit(G1_AVR_FrequencyBlockU_x_1, G1_AVR_DL0);
endwhen(63) 
when(initial(), 64) 
  reinit(SM2_G_s, 0);
endwhen(64) 
when(initial(), 65) 
  reinit(SM2_G_Yr, SM2_G_PsiR);
endwhen(65) 
when(initial(), 66) 
  reinit(SM2_G_Yrd, SM2_G_PsiRD);
endwhen(66) 
when(initial(), 67) 
  reinit(SM2_G_Yrq, SM2_G_PsiRQ);
endwhen(67) 
when(initial(), 68) 
  reinit(SM2_G_Mu, SM2_G_Mu0);
endwhen(68) 
when(initial(), 69) 
  reinit(SM2_AVR_FrequencyBlockU_x_1, SM2_AVR_DL0);
endwhen(69) 
InitialSection
/* No equations */
DefaultSection
InitializeData(1)
EndTranslatedEquations

#include <dsblock6.c>

PreNonAlias(0)
StartNonAlias(0)
DeclareParameter("G1.G.TgenOff", "", 0, 1000, 0.0,0.0,0.0,0,0)
DeclareParameter("G1.G.dTgenOff", "", 1, 10, 0.0,0.0,0.0,0,0)
DeclareParameter("G1.G.Pg", "", 2, (-0.35), 0.0,0.0,0.0,0,0)
DeclareParameter("G1.G.Qg", "", 3, (-0.2), 0.0,0.0,0.0,0,0)
DeclareParameter("G1.G.Ut", "", 4, 1, 0.0,0.0,0.0,0,0)
DeclareParameter("G1.G.Xd", "Продольное индуктивное сопротивление", 5, 3.223, \
0.0,0.0,0.0,0,0)
DeclareParameter("G1.G.Xq", "Поперечное индуктивное сопротивление", 6, 2.089, \
0.0,0.0,0.0,0,0)
DeclareParameter("G1.G.Xs", "Индуктивное сопротивление рассеяния", 7, 0.257, \
0.0,0.0,0.0,0,0)
DeclareParameter("G1.G.X1d", "Переходное продольное индуктивное сопротивление", \
8, 0.829, 0.0,0.0,0.0,0,0)
DeclareParameter("G1.G.X2d", "Сверхпереходное продольное индуктивное сопротивление"\
, 9, 0.485, 0.0,0.0,0.0,0,0)
DeclareParameter("G1.G.X2q", "Сверхпереходное поперечное индуктивное сопротивление"\
, 10, 0.457, 0.0,0.0,0.0,0,0)
DeclareParameter("G1.G.Rf", "Активное сопротивление обмотки возбуждения", 11, \
0.00178, 0.0,0.0,0.0,0,0)
DeclareParameter("G1.G.R1d", "Активное сопротивление ДК в продольной оси", 12, \
0.0127, 0.0,0.0,0.0,0,0)
DeclareParameter("G1.G.R1q", "Активное сопротивление ДК в поперечной оси", 13, \
0.00871, 0.0,0.0,0.0,0,0)
DeclareParameter("G1.G.Tj", "Механическая инерционная постоянная", 14, 2.45, \
0.0,0.0,0.0,0,0)
DeclareParameter("G1.G.Xt", "Индуктивное сопротивление трансформатора", 15, 0, \
0.0,0.0,0.0,0,0)
DeclareParameter("G1.G.Sigma", "Коэффициент статизма регулятора турбины", 16, \
0.0475, 0.0,0.0,0.0,0,0)
DeclareParameter("G1.G.TauC", "Постоянная времени сервомотора", 17, 99999, \
0.0,0.0,0.0,0,0)
DeclareParameter("G1.G.Mt_max", "Верхнее ограничение момента турбины", 18, 0, \
0.0,0.0,0.0,0,0)
DeclareParameter("G1.G.Mt_min", "Нижнее ограничение момента турбины", 19, (-0.5)\
, 0.0,0.0,0.0,0,0)
DeclareVariable("G1.G.dEr", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("G1.G.PI", "", 3.14159265358979, 0.0,0.0,0.0,0,1)
DeclareVariable("G1.G.Wc", "", 314.159265358979, 0.0,0.0,0.0,0,1)
DeclareVariable("G1.G.Ra", "", 0, 0.0,0.0,0.0,0,1)
DeclareVariable("G1.G.Rt", "", 0, 0.0,0.0,0.0,0,1)
DeclareVariable("G1.G.EQ", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("G1.G.Dg", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("G1.G.Uq", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("G1.G.Ud", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("G1.G.Id", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("G1.G.Iq", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("G1.G.Mt", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("G1.G.Eiq", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("G1.G.Ir", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("G1.G.Uf", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("G1.G.Eq", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("G1.G.Er0", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("G1.G.PsiR", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("G1.G.PsiRD", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("G1.G.PsiRQ", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("G1.G.Er_max", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("G1.G.Er_min", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("G1.G.Uf_full", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("G1.G.Xad", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("G1.G.Xaq", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("G1.G.X2dt", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("G1.G.X2qt", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("G1.G.Rs", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("G1.G.Xsf", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("G1.G.Xs1d", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("G1.G.Xs1q", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("G1.G.X1", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("G1.G.X2", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("G1.G.X3", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("G1.G.Ugen", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("G1.G.Mu0", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("G1.G.Ro", "", 0, 0.0,0.0,0.0,0,0)
DeclareState("G1.G.Mu", "", 0, 0, 0.0,0.0,0.0,0,0)
DeclareDerivative("G1.G.der(Mu)", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("G1.G.Mt_pp", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("G1.G.Pgen", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("G1.G.Qgen", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("G1.G.DeltaIJ", "", 0, 0.0,0.0,0.0,0,1)
DeclareState("G1.G.Yr", "", 1, 0, 0.0,0.0,0.0,0,0)
DeclareDerivative("G1.G.der(Yr)", "", 0, 0.0,0.0,0.0,0,0)
DeclareState("G1.G.Yrd", "", 2, 0, 0.0,0.0,0.0,0,0)
DeclareDerivative("G1.G.der(Yrd)", "", 0, 0.0,0.0,0.0,0,0)
DeclareState("G1.G.Yrq", "", 3, 0, 0.0,0.0,0.0,0,0)
DeclareDerivative("G1.G.der(Yrq)", "", 0, 0.0,0.0,0.0,0,0)
DeclareState("G1.G.s", "", 4, 0, 0.0,0.0,0.0,0,0)
DeclareDerivative("G1.G.der(s)", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("G1.G.Me", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("G1.G.Yad", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("G1.G.Yaq", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("G1.G.iq", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("G1.G.id", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("G1.G.ir", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("G1.G.ird", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("G1.G.irq", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("G1.G.E11d", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("G1.G.E11q", "", 0, 0.0,0.0,0.0,0,0)
DeclareParameter("G1.AVR.K0u", "", 20, (-10), 0.0,0.0,0.0,0,0)
DeclareParameter("G1.AVR.K1u", "", 21, 0, 0.0,0.0,0.0,0,0)
DeclareParameter("G1.AVR.K0w", "", 22, 0, 0.0,0.0,0.0,0,0)
DeclareParameter("G1.AVR.K1w", "", 23, 0, 0.0,0.0,0.0,0,0)
DeclareParameter("G1.AVR.K1if", "", 24, 0, 0.0,0.0,0.0,0,0)
DeclareParameter("G1.AVR.DL0", "", 25, 0, 0.0,0.0,0.0,0,0)
DeclareParameter("G1.AVR.Tokp", "", 26, 0.05, 0.0,0.0,0.0,0,0)
DeclareVariable("G1.AVR.T0u", "", 0.02, 0.0,0.0,0.0,0,1)
DeclareVariable("G1.AVR.T1u", "", 0.039, 0.0,0.0,0.0,0,1)
DeclareVariable("G1.AVR.Tfb", "", 0.07, 0.0,0.0,0.0,0,1)
DeclareVariable("G1.AVR.T0w", "", 1, 0.0,0.0,0.0,0,1)
DeclareVariable("G1.AVR.T1w", "", 0.026, 0.0,0.0,0.0,0,1)
DeclareVariable("G1.AVR.T1if", "", 0.03, 0.0,0.0,0.0,0,1)
DeclareVariable("G1.AVR.VoltageDeviation.b[1]", "Numerator coefficients of transfer function."\
, 0, 0.0,0.0,0.0,0,1)
DeclareVariable("G1.AVR.VoltageDeviation.a[1]", "Denominator coefficients of transfer function."\
, 0.02, 0.0,0.0,0.0,0,1)
DeclareVariable("G1.AVR.VoltageDeviation.a[2]", "Denominator coefficients of transfer function."\
, 1, 0.0,0.0,0.0,0,1)
DeclareState("G1.AVR.VoltageDeviation.x[1]", "State of transfer function from controller canonical form"\
, 5, 0, 0.0,0.0,0.0,0,0)
DeclareDerivative("G1.AVR.VoltageDeviation.der(x[1])", "State of transfer function from controller canonical form"\
, 0, 0.0,0.0,0.0,0,0)
DeclareVariable("G1.AVR.VoltageDeviation.na", "Size of Denominator of transfer function."\
, 2, 0.0,0.0,0.0,0,1)
DeclareVariable("G1.AVR.VoltageDeviation.nb", "Size of Numerator of transfer function."\
, 1, 0.0,0.0,0.0,0,1)
DeclareVariable("G1.AVR.VoltageDeviation.nx", "", 1, 0.0,0.0,0.0,0,1)
DeclareVariable("G1.AVR.VoltageDeviation.u", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("G1.AVR.VoltageDeviation.y", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("G1.AVR.VoltageDerivative.b[1]", "Numerator coefficients of transfer function."\
, 0, 0.0,0.0,0.0,0,1)
DeclareVariable("G1.AVR.VoltageDerivative.b[2]", "Numerator coefficients of transfer function."\
, 0, 0.0,0.0,0.0,0,1)
DeclareVariable("G1.AVR.VoltageDerivative.a[1]", "Denominator coefficients of transfer function."\
, 0.039, 0.0,0.0,0.0,0,1)
DeclareVariable("G1.AVR.VoltageDerivative.a[2]", "Denominator coefficients of transfer function."\
, 1, 0.0,0.0,0.0,0,1)
DeclareState("G1.AVR.VoltageDerivative.x[1]", "State of transfer function from controller canonical form"\
, 6, 0, 0.0,0.0,0.0,0,0)
DeclareDerivative("G1.AVR.VoltageDerivative.der(x[1])", "State of transfer function from controller canonical form"\
, 0, 0.0,0.0,0.0,0,0)
DeclareVariable("G1.AVR.VoltageDerivative.na", "Size of Denominator of transfer function."\
, 2, 0.0,0.0,0.0,0,1)
DeclareVariable("G1.AVR.VoltageDerivative.nb", "Size of Numerator of transfer function."\
, 2, 0.0,0.0,0.0,0,1)
DeclareVariable("G1.AVR.VoltageDerivative.nx", "", 1, 0.0,0.0,0.0,0,1)
DeclareVariable("G1.AVR.VoltageDerivative.y", "", 0, 0.0,0.0,0.0,0,0)
DeclareParameter("G1.AVR.FrequencyBlockD.b[1]", "Numerator coefficients of transfer function."\
, 27, 1, 0.0,0.0,0.0,0,0)
DeclareVariable("G1.AVR.FrequencyBlockD.a[1]", "Denominator coefficients of transfer function."\
, 0.07, 0.0,0.0,0.0,0,1)
DeclareVariable("G1.AVR.FrequencyBlockD.a[2]", "Denominator coefficients of transfer function."\
, 1, 0.0,0.0,0.0,0,1)
DeclareState("G1.AVR.FrequencyBlockD.x[1]", "State of transfer function from controller canonical form"\
, 7, 0, 0.0,0.0,0.0,0,0)
DeclareDerivative("G1.AVR.FrequencyBlockD.der(x[1])", "State of transfer function from controller canonical form"\
, 0, 0.0,0.0,0.0,0,0)
DeclareVariable("G1.AVR.FrequencyBlockD.na", "Size of Denominator of transfer function."\
, 2, 0.0,0.0,0.0,0,1)
DeclareVariable("G1.AVR.FrequencyBlockD.nb", "Size of Numerator of transfer function."\
, 1, 0.0,0.0,0.0,0,1)
DeclareVariable("G1.AVR.FrequencyBlockD.nx", "", 1, 0.0,0.0,0.0,0,1)
DeclareVariable("G1.AVR.FrequencyBlockD.u", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("G1.AVR.FrequencyBlockD.y", "", 0, 0.0,0.0,0.0,0,0)
DeclareParameter("G1.AVR.FrequencyBlockU.b[1]", "Numerator coefficients of transfer function."\
, 28, 1, 0.0,0.0,0.0,0,0)
DeclareParameter("G1.AVR.FrequencyBlockU.b[2]", "Numerator coefficients of transfer function."\
, 29, 0, 0.0,0.0,0.0,0,0)
DeclareVariable("G1.AVR.FrequencyBlockU.a[1]", "Denominator coefficients of transfer function."\
, 0.07, 0.0,0.0,0.0,0,1)
DeclareVariable("G1.AVR.FrequencyBlockU.a[2]", "Denominator coefficients of transfer function."\
, 1, 0.0,0.0,0.0,0,1)
DeclareState("G1.AVR.FrequencyBlockU.x[1]", "State of transfer function from controller canonical form"\
, 8, 0, 0.0,0.0,0.0,0,0)
DeclareDerivative("G1.AVR.FrequencyBlockU.der(x[1])", "State of transfer function from controller canonical form"\
, 0, 0.0,0.0,0.0,0,0)
DeclareVariable("G1.AVR.FrequencyBlockU.na", "Size of Denominator of transfer function."\
, 2, 0.0,0.0,0.0,0,1)
DeclareVariable("G1.AVR.FrequencyBlockU.nb", "Size of Numerator of transfer function."\
, 2, 0.0,0.0,0.0,0,1)
DeclareVariable("G1.AVR.FrequencyBlockU.nx", "", 1, 0.0,0.0,0.0,0,1)
DeclareVariable("G1.AVR.FrequencyBlockU.u", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("G1.AVR.FrequencyBlockU.y", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("G1.AVR.FrequencyDeviation.b[1]", "Numerator coefficients of transfer function."\
, 0, 0.0,0.0,0.0,0,1)
DeclareVariable("G1.AVR.FrequencyDeviation.b[2]", "Numerator coefficients of transfer function."\
, 0, 0.0,0.0,0.0,0,1)
DeclareVariable("G1.AVR.FrequencyDeviation.a[1]", "Denominator coefficients of transfer function."\
, 1, 0.0,0.0,0.0,0,1)
DeclareVariable("G1.AVR.FrequencyDeviation.a[2]", "Denominator coefficients of transfer function."\
, 1, 0.0,0.0,0.0,0,1)
DeclareState("G1.AVR.FrequencyDeviation.x[1]", "State of transfer function from controller canonical form"\
, 9, 0, 0.0,0.0,0.0,0,0)
DeclareDerivative("G1.AVR.FrequencyDeviation.der(x[1])", "State of transfer function from controller canonical form"\
, 0, 0.0,0.0,0.0,0,0)
DeclareVariable("G1.AVR.FrequencyDeviation.na", "Size of Denominator of transfer function."\
, 2, 0.0,0.0,0.0,0,1)
DeclareVariable("G1.AVR.FrequencyDeviation.nb", "Size of Numerator of transfer function."\
, 2, 0.0,0.0,0.0,0,1)
DeclareVariable("G1.AVR.FrequencyDeviation.nx", "", 1, 0.0,0.0,0.0,0,1)
DeclareVariable("G1.AVR.FrequencyDeviation.u", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("G1.AVR.FrequencyDeviation.y", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("G1.AVR.FrequencyDerivative.b[1]", "Numerator coefficients of transfer function."\
, 0, 0.0,0.0,0.0,0,1)
DeclareVariable("G1.AVR.FrequencyDerivative.b[2]", "Numerator coefficients of transfer function."\
, 0, 0.0,0.0,0.0,0,1)
DeclareVariable("G1.AVR.FrequencyDerivative.a[1]", "Denominator coefficients of transfer function."\
, 0.026, 0.0,0.0,0.0,0,1)
DeclareVariable("G1.AVR.FrequencyDerivative.a[2]", "Denominator coefficients of transfer function."\
, 1, 0.0,0.0,0.0,0,1)
DeclareState("G1.AVR.FrequencyDerivative.x[1]", "State of transfer function from controller canonical form"\
, 10, 0, 0.0,0.0,0.0,0,0)
DeclareDerivative("G1.AVR.FrequencyDerivative.der(x[1])", "State of transfer function from controller canonical form"\
, 0, 0.0,0.0,0.0,0,0)
DeclareVariable("G1.AVR.FrequencyDerivative.na", "Size of Denominator of transfer function."\
, 2, 0.0,0.0,0.0,0,1)
DeclareVariable("G1.AVR.FrequencyDerivative.nb", "Size of Numerator of transfer function."\
, 2, 0.0,0.0,0.0,0,1)
DeclareVariable("G1.AVR.FrequencyDerivative.nx", "", 1, 0.0,0.0,0.0,0,1)
DeclareVariable("G1.AVR.FrequencyDerivative.y", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("G1.AVR.ExcitationCurrent.b[1]", "Numerator coefficients of transfer function."\
, 0, 0.0,0.0,0.0,0,1)
DeclareVariable("G1.AVR.ExcitationCurrent.b[2]", "Numerator coefficients of transfer function."\
, 0, 0.0,0.0,0.0,0,1)
DeclareVariable("G1.AVR.ExcitationCurrent.a[1]", "Denominator coefficients of transfer function."\
, 0.03, 0.0,0.0,0.0,0,1)
DeclareVariable("G1.AVR.ExcitationCurrent.a[2]", "Denominator coefficients of transfer function."\
, 1, 0.0,0.0,0.0,0,1)
DeclareState("G1.AVR.ExcitationCurrent.x[1]", "State of transfer function from controller canonical form"\
, 11, 0, 0.0,0.0,0.0,0,0)
DeclareDerivative("G1.AVR.ExcitationCurrent.der(x[1])", "State of transfer function from controller canonical form"\
, 0, 0.0,0.0,0.0,0,0)
DeclareVariable("G1.AVR.ExcitationCurrent.na", "Size of Denominator of transfer function."\
, 2, 0.0,0.0,0.0,0,1)
DeclareVariable("G1.AVR.ExcitationCurrent.nb", "Size of Numerator of transfer function."\
, 2, 0.0,0.0,0.0,0,1)
DeclareVariable("G1.AVR.ExcitationCurrent.nx", "", 1, 0.0,0.0,0.0,0,1)
DeclareVariable("G1.AVR.ExcitationCurrent.u", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("G1.AVR.ExcitationCurrent.y", "", 0, 0.0,0.0,0.0,0,0)
DeclareParameter("G1.AVR.SimpleExciter.b[1]", "Numerator coefficients of transfer function."\
, 30, 1, 0.0,0.0,0.0,0,0)
DeclareVariable("G1.AVR.SimpleExciter.a[1]", "Denominator coefficients of transfer function."\
, 0, 0.0,0.0,0.0,0,1)
DeclareVariable("G1.AVR.SimpleExciter.a[2]", "Denominator coefficients of transfer function."\
, 1, 0.0,0.0,0.0,0,1)
DeclareState("G1.AVR.SimpleExciter.x[1]", "State of transfer function from controller canonical form"\
, 12, 0, 0.0,0.0,0.0,0,0)
DeclareDerivative("G1.AVR.SimpleExciter.der(x[1])", "State of transfer function from controller canonical form"\
, 0, 0.0,0.0,0.0,0,0)
DeclareVariable("G1.AVR.SimpleExciter.na", "Size of Denominator of transfer function."\
, 2, 0.0,0.0,0.0,0,1)
DeclareVariable("G1.AVR.SimpleExciter.nb", "Size of Numerator of transfer function."\
, 1, 0.0,0.0,0.0,0,1)
DeclareVariable("G1.AVR.SimpleExciter.nx", "", 1, 0.0,0.0,0.0,0,1)
DeclareVariable("G1.AVR.SimpleExciter.u", "", 0, 0.0,0.0,0.0,0,0)
DeclareParameter("L0102.Rline", "", 31, 0.01, 0.0,0.0,0.0,0,0)
DeclareParameter("L0102.Xline", "", 32, 0.1, 0.0,0.0,0.0,0,0)
DeclareParameter("L0102.Bline", "", 33, 0, 0.0,0.0,0.0,0,0)
DeclareParameter("L0102.TLineOff", "", 34, 1000, 0.0,0.0,0.0,0,0)
DeclareParameter("L0102.dTLineOff", "", 35, 10, 0.0,0.0,0.0,0,0)
DeclareParameter("L0102.Koff", "", 36, 100000, 0.0,0.0,0.0,0,0)
DeclareVariable("L0102.U1d", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("L0102.U1q", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("L0102.U2d", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("L0102.U2q", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("L0102.I12d", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("L0102.I12q", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("L0102.I12m", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("L0102.U1m", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("L0102.U2m", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("L0102.I1d", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("L0102.I1q", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("L0102.I2d", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("L0102.I2q", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("L0102.Idc1", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("L0102.Iqc1", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("L0102.Idc2", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("L0102.Iqc2", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("L0102.DU1", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("L0102.DU2", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("L0102.Bnn", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("L0102.P1", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("L0102.Q1", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("L0102.P2", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("L0102.Q2", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("L0102.RL", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("L0102.XL", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("L0102.BL", "", 0, 0.0,0.0,0.0,0,0)
DeclareParameter("SM2.G.TgenOff", "", 37, 1000, 0.0,0.0,0.0,0,0)
DeclareParameter("SM2.G.dTgenOff", "", 38, 10, 0.0,0.0,0.0,0,0)
DeclareParameter("SM2.G.Pg", "", 39, (-0.35), 0.0,0.0,0.0,0,0)
DeclareParameter("SM2.G.Qg", "", 40, (-0.2), 0.0,0.0,0.0,0,0)
DeclareParameter("SM2.G.Ut", "", 41, 1, 0.0,0.0,0.0,0,0)
DeclareParameter("SM2.G.Xd", "Продольное индуктивное сопротивление", 42, 3.223, \
0.0,0.0,0.0,0,0)
DeclareParameter("SM2.G.Xq", "Поперечное индуктивное сопротивление", 43, 2.089, \
0.0,0.0,0.0,0,0)
DeclareParameter("SM2.G.Xs", "Индуктивное сопротивление рассеяния", 44, 0.257, \
0.0,0.0,0.0,0,0)
DeclareParameter("SM2.G.X1d", "Переходное продольное индуктивное сопротивление"\
, 45, 0.829, 0.0,0.0,0.0,0,0)
DeclareParameter("SM2.G.X2d", "Сверхпереходное продольное индуктивное сопротивление"\
, 46, 0.485, 0.0,0.0,0.0,0,0)
DeclareParameter("SM2.G.X2q", "Сверхпереходное поперечное индуктивное сопротивление"\
, 47, 0.457, 0.0,0.0,0.0,0,0)
DeclareParameter("SM2.G.Rf", "Активное сопротивление обмотки возбуждения", 48, \
0.00178, 0.0,0.0,0.0,0,0)
DeclareParameter("SM2.G.R1d", "Активное сопротивление ДК в продольной оси", 49, \
0.0127, 0.0,0.0,0.0,0,0)
DeclareParameter("SM2.G.R1q", "Активное сопротивление ДК в поперечной оси", 50, \
0.00871, 0.0,0.0,0.0,0,0)
DeclareParameter("SM2.G.Tj", "Механическая инерционная постоянная", 51, 2.45, \
0.0,0.0,0.0,0,0)
DeclareParameter("SM2.G.Xt", "Индуктивное сопротивление трансформатора", 52, 0, \
0.0,0.0,0.0,0,0)
DeclareParameter("SM2.G.Sigma", "Коэффициент статизма регулятора турбины", 53, \
0.0475, 0.0,0.0,0.0,0,0)
DeclareParameter("SM2.G.TauC", "Постоянная времени сервомотора", 54, 99999, \
0.0,0.0,0.0,0,0)
DeclareParameter("SM2.G.Mt_max", "Верхнее ограничение момента турбины", 55, 0, \
0.0,0.0,0.0,0,0)
DeclareParameter("SM2.G.Mt_min", "Нижнее ограничение момента турбины", 56, (-0.5\
), 0.0,0.0,0.0,0,0)
DeclareVariable("SM2.G.dEr", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("SM2.G.PI", "", 3.14159265358979, 0.0,0.0,0.0,0,1)
DeclareVariable("SM2.G.Wc", "", 314.159265358979, 0.0,0.0,0.0,0,1)
DeclareVariable("SM2.G.Ra", "", 0, 0.0,0.0,0.0,0,1)
DeclareVariable("SM2.G.Rt", "", 0, 0.0,0.0,0.0,0,1)
DeclareVariable("SM2.G.EQ", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("SM2.G.Dg", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("SM2.G.Uq", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("SM2.G.Ud", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("SM2.G.Id", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("SM2.G.Iq", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("SM2.G.Mt", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("SM2.G.Eiq", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("SM2.G.Ir", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("SM2.G.Uf", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("SM2.G.Eq", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("SM2.G.Er0", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("SM2.G.PsiR", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("SM2.G.PsiRD", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("SM2.G.PsiRQ", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("SM2.G.Er_max", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("SM2.G.Er_min", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("SM2.G.Uf_full", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("SM2.G.Xad", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("SM2.G.Xaq", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("SM2.G.X2dt", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("SM2.G.X2qt", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("SM2.G.Rs", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("SM2.G.Xsf", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("SM2.G.Xs1d", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("SM2.G.Xs1q", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("SM2.G.X1", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("SM2.G.X2", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("SM2.G.X3", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("SM2.G.Ugen", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("SM2.G.Mu0", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("SM2.G.Ro", "", 0, 0.0,0.0,0.0,0,0)
DeclareState("SM2.G.Mu", "", 13, 0, 0.0,0.0,0.0,0,0)
DeclareDerivative("SM2.G.der(Mu)", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("SM2.G.Mt_pp", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("SM2.G.Pgen", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("SM2.G.Qgen", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("SM2.G.IdG", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("SM2.G.IqG", "", 0, 0.0,0.0,0.0,0,0)
DeclareState("SM2.G.Yr", "", 14, 0, 0.0,0.0,0.0,0,0)
DeclareDerivative("SM2.G.der(Yr)", "", 0, 0.0,0.0,0.0,0,0)
DeclareState("SM2.G.Yrd", "", 15, 0, 0.0,0.0,0.0,0,0)
DeclareDerivative("SM2.G.der(Yrd)", "", 0, 0.0,0.0,0.0,0,0)
DeclareState("SM2.G.Yrq", "", 16, 0, 0.0,0.0,0.0,0,0)
DeclareDerivative("SM2.G.der(Yrq)", "", 0, 0.0,0.0,0.0,0,0)
DeclareState("SM2.G.s", "", 17, 0, 0.0,0.0,0.0,0,0)
DeclareDerivative("SM2.G.der(s)", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("SM2.G.Me", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("SM2.G.Yad", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("SM2.G.Yaq", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("SM2.G.iq", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("SM2.G.id", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("SM2.G.ir", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("SM2.G.ird", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("SM2.G.irq", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("SM2.G.ud", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("SM2.G.uq", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("SM2.G.E11d", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("SM2.G.E11q", "", 0, 0.0,0.0,0.0,0,0)
DeclareParameter("SM2.AVR.K0u", "", 57, (-10), 0.0,0.0,0.0,0,0)
DeclareParameter("SM2.AVR.K1u", "", 58, 0, 0.0,0.0,0.0,0,0)
DeclareParameter("SM2.AVR.K0w", "", 59, 0, 0.0,0.0,0.0,0,0)
DeclareParameter("SM2.AVR.K1w", "", 60, 0, 0.0,0.0,0.0,0,0)
DeclareParameter("SM2.AVR.K1if", "", 61, 0, 0.0,0.0,0.0,0,0)
DeclareParameter("SM2.AVR.DL0", "", 62, 0, 0.0,0.0,0.0,0,0)
DeclareParameter("SM2.AVR.Tokp", "", 63, 0.05, 0.0,0.0,0.0,0,0)
DeclareVariable("SM2.AVR.T0u", "", 0.02, 0.0,0.0,0.0,0,1)
DeclareVariable("SM2.AVR.T1u", "", 0.039, 0.0,0.0,0.0,0,1)
DeclareVariable("SM2.AVR.Tfb", "", 0.07, 0.0,0.0,0.0,0,1)
DeclareVariable("SM2.AVR.T0w", "", 1, 0.0,0.0,0.0,0,1)
DeclareVariable("SM2.AVR.T1w", "", 0.026, 0.0,0.0,0.0,0,1)
DeclareVariable("SM2.AVR.T1if", "", 0.03, 0.0,0.0,0.0,0,1)
DeclareVariable("SM2.AVR.VoltageDeviation.b[1]", "Numerator coefficients of transfer function."\
, 0, 0.0,0.0,0.0,0,1)
DeclareVariable("SM2.AVR.VoltageDeviation.a[1]", "Denominator coefficients of transfer function."\
, 0.02, 0.0,0.0,0.0,0,1)
DeclareVariable("SM2.AVR.VoltageDeviation.a[2]", "Denominator coefficients of transfer function."\
, 1, 0.0,0.0,0.0,0,1)
DeclareState("SM2.AVR.VoltageDeviation.x[1]", "State of transfer function from controller canonical form"\
, 18, 0, 0.0,0.0,0.0,0,0)
DeclareDerivative("SM2.AVR.VoltageDeviation.der(x[1])", "State of transfer function from controller canonical form"\
, 0, 0.0,0.0,0.0,0,0)
DeclareVariable("SM2.AVR.VoltageDeviation.na", "Size of Denominator of transfer function."\
, 2, 0.0,0.0,0.0,0,1)
DeclareVariable("SM2.AVR.VoltageDeviation.nb", "Size of Numerator of transfer function."\
, 1, 0.0,0.0,0.0,0,1)
DeclareVariable("SM2.AVR.VoltageDeviation.nx", "", 1, 0.0,0.0,0.0,0,1)
DeclareVariable("SM2.AVR.VoltageDeviation.u", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("SM2.AVR.VoltageDeviation.y", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("SM2.AVR.VoltageDerivative.b[1]", "Numerator coefficients of transfer function."\
, 0, 0.0,0.0,0.0,0,1)
DeclareVariable("SM2.AVR.VoltageDerivative.b[2]", "Numerator coefficients of transfer function."\
, 0, 0.0,0.0,0.0,0,1)
DeclareVariable("SM2.AVR.VoltageDerivative.a[1]", "Denominator coefficients of transfer function."\
, 0.039, 0.0,0.0,0.0,0,1)
DeclareVariable("SM2.AVR.VoltageDerivative.a[2]", "Denominator coefficients of transfer function."\
, 1, 0.0,0.0,0.0,0,1)
DeclareState("SM2.AVR.VoltageDerivative.x[1]", "State of transfer function from controller canonical form"\
, 19, 0, 0.0,0.0,0.0,0,0)
DeclareDerivative("SM2.AVR.VoltageDerivative.der(x[1])", "State of transfer function from controller canonical form"\
, 0, 0.0,0.0,0.0,0,0)
DeclareVariable("SM2.AVR.VoltageDerivative.na", "Size of Denominator of transfer function."\
, 2, 0.0,0.0,0.0,0,1)
DeclareVariable("SM2.AVR.VoltageDerivative.nb", "Size of Numerator of transfer function."\
, 2, 0.0,0.0,0.0,0,1)
DeclareVariable("SM2.AVR.VoltageDerivative.nx", "", 1, 0.0,0.0,0.0,0,1)
DeclareVariable("SM2.AVR.VoltageDerivative.y", "", 0, 0.0,0.0,0.0,0,0)
DeclareParameter("SM2.AVR.FrequencyBlockD.b[1]", "Numerator coefficients of transfer function."\
, 64, 1, 0.0,0.0,0.0,0,0)
DeclareVariable("SM2.AVR.FrequencyBlockD.a[1]", "Denominator coefficients of transfer function."\
, 0.07, 0.0,0.0,0.0,0,1)
DeclareVariable("SM2.AVR.FrequencyBlockD.a[2]", "Denominator coefficients of transfer function."\
, 1, 0.0,0.0,0.0,0,1)
DeclareState("SM2.AVR.FrequencyBlockD.x[1]", "State of transfer function from controller canonical form"\
, 20, 0, 0.0,0.0,0.0,0,0)
DeclareDerivative("SM2.AVR.FrequencyBlockD.der(x[1])", "State of transfer function from controller canonical form"\
, 0, 0.0,0.0,0.0,0,0)
DeclareVariable("SM2.AVR.FrequencyBlockD.na", "Size of Denominator of transfer function."\
, 2, 0.0,0.0,0.0,0,1)
DeclareVariable("SM2.AVR.FrequencyBlockD.nb", "Size of Numerator of transfer function."\
, 1, 0.0,0.0,0.0,0,1)
DeclareVariable("SM2.AVR.FrequencyBlockD.nx", "", 1, 0.0,0.0,0.0,0,1)
DeclareVariable("SM2.AVR.FrequencyBlockD.u", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("SM2.AVR.FrequencyBlockD.y", "", 0, 0.0,0.0,0.0,0,0)
DeclareParameter("SM2.AVR.FrequencyBlockU.b[1]", "Numerator coefficients of transfer function."\
, 65, 1, 0.0,0.0,0.0,0,0)
DeclareParameter("SM2.AVR.FrequencyBlockU.b[2]", "Numerator coefficients of transfer function."\
, 66, 0, 0.0,0.0,0.0,0,0)
DeclareVariable("SM2.AVR.FrequencyBlockU.a[1]", "Denominator coefficients of transfer function."\
, 0.07, 0.0,0.0,0.0,0,1)
DeclareVariable("SM2.AVR.FrequencyBlockU.a[2]", "Denominator coefficients of transfer function."\
, 1, 0.0,0.0,0.0,0,1)
DeclareState("SM2.AVR.FrequencyBlockU.x[1]", "State of transfer function from controller canonical form"\
, 21, 0, 0.0,0.0,0.0,0,0)
DeclareDerivative("SM2.AVR.FrequencyBlockU.der(x[1])", "State of transfer function from controller canonical form"\
, 0, 0.0,0.0,0.0,0,0)
DeclareVariable("SM2.AVR.FrequencyBlockU.na", "Size of Denominator of transfer function."\
, 2, 0.0,0.0,0.0,0,1)
DeclareVariable("SM2.AVR.FrequencyBlockU.nb", "Size of Numerator of transfer function."\
, 2, 0.0,0.0,0.0,0,1)
DeclareVariable("SM2.AVR.FrequencyBlockU.nx", "", 1, 0.0,0.0,0.0,0,1)
DeclareVariable("SM2.AVR.FrequencyBlockU.u", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("SM2.AVR.FrequencyBlockU.y", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("SM2.AVR.FrequencyDeviation.b[1]", "Numerator coefficients of transfer function."\
, 0, 0.0,0.0,0.0,0,1)
DeclareVariable("SM2.AVR.FrequencyDeviation.b[2]", "Numerator coefficients of transfer function."\
, 0, 0.0,0.0,0.0,0,1)
DeclareVariable("SM2.AVR.FrequencyDeviation.a[1]", "Denominator coefficients of transfer function."\
, 1, 0.0,0.0,0.0,0,1)
DeclareVariable("SM2.AVR.FrequencyDeviation.a[2]", "Denominator coefficients of transfer function."\
, 1, 0.0,0.0,0.0,0,1)
DeclareState("SM2.AVR.FrequencyDeviation.x[1]", "State of transfer function from controller canonical form"\
, 22, 0, 0.0,0.0,0.0,0,0)
DeclareDerivative("SM2.AVR.FrequencyDeviation.der(x[1])", "State of transfer function from controller canonical form"\
, 0, 0.0,0.0,0.0,0,0)
DeclareVariable("SM2.AVR.FrequencyDeviation.na", "Size of Denominator of transfer function."\
, 2, 0.0,0.0,0.0,0,1)
DeclareVariable("SM2.AVR.FrequencyDeviation.nb", "Size of Numerator of transfer function."\
, 2, 0.0,0.0,0.0,0,1)
DeclareVariable("SM2.AVR.FrequencyDeviation.nx", "", 1, 0.0,0.0,0.0,0,1)
DeclareVariable("SM2.AVR.FrequencyDeviation.u", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("SM2.AVR.FrequencyDeviation.y", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("SM2.AVR.FrequencyDerivative.b[1]", "Numerator coefficients of transfer function."\
, 0, 0.0,0.0,0.0,0,1)
DeclareVariable("SM2.AVR.FrequencyDerivative.b[2]", "Numerator coefficients of transfer function."\
, 0, 0.0,0.0,0.0,0,1)
DeclareVariable("SM2.AVR.FrequencyDerivative.a[1]", "Denominator coefficients of transfer function."\
, 0.026, 0.0,0.0,0.0,0,1)
DeclareVariable("SM2.AVR.FrequencyDerivative.a[2]", "Denominator coefficients of transfer function."\
, 1, 0.0,0.0,0.0,0,1)
DeclareState("SM2.AVR.FrequencyDerivative.x[1]", "State of transfer function from controller canonical form"\
, 23, 0, 0.0,0.0,0.0,0,0)
DeclareDerivative("SM2.AVR.FrequencyDerivative.der(x[1])", "State of transfer function from controller canonical form"\
, 0, 0.0,0.0,0.0,0,0)
DeclareVariable("SM2.AVR.FrequencyDerivative.na", "Size of Denominator of transfer function."\
, 2, 0.0,0.0,0.0,0,1)
DeclareVariable("SM2.AVR.FrequencyDerivative.nb", "Size of Numerator of transfer function."\
, 2, 0.0,0.0,0.0,0,1)
DeclareVariable("SM2.AVR.FrequencyDerivative.nx", "", 1, 0.0,0.0,0.0,0,1)
DeclareVariable("SM2.AVR.FrequencyDerivative.y", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("SM2.AVR.ExcitationCurrent.b[1]", "Numerator coefficients of transfer function."\
, 0, 0.0,0.0,0.0,0,1)
DeclareVariable("SM2.AVR.ExcitationCurrent.b[2]", "Numerator coefficients of transfer function."\
, 0, 0.0,0.0,0.0,0,1)
DeclareVariable("SM2.AVR.ExcitationCurrent.a[1]", "Denominator coefficients of transfer function."\
, 0.03, 0.0,0.0,0.0,0,1)
DeclareVariable("SM2.AVR.ExcitationCurrent.a[2]", "Denominator coefficients of transfer function."\
, 1, 0.0,0.0,0.0,0,1)
DeclareState("SM2.AVR.ExcitationCurrent.x[1]", "State of transfer function from controller canonical form"\
, 24, 0, 0.0,0.0,0.0,0,0)
DeclareDerivative("SM2.AVR.ExcitationCurrent.der(x[1])", "State of transfer function from controller canonical form"\
, 0, 0.0,0.0,0.0,0,0)
DeclareVariable("SM2.AVR.ExcitationCurrent.na", "Size of Denominator of transfer function."\
, 2, 0.0,0.0,0.0,0,1)
DeclareVariable("SM2.AVR.ExcitationCurrent.nb", "Size of Numerator of transfer function."\
, 2, 0.0,0.0,0.0,0,1)
DeclareVariable("SM2.AVR.ExcitationCurrent.nx", "", 1, 0.0,0.0,0.0,0,1)
DeclareVariable("SM2.AVR.ExcitationCurrent.u", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("SM2.AVR.ExcitationCurrent.y", "", 0, 0.0,0.0,0.0,0,0)
DeclareParameter("SM2.AVR.SimpleExciter.b[1]", "Numerator coefficients of transfer function."\
, 67, 1, 0.0,0.0,0.0,0,0)
DeclareVariable("SM2.AVR.SimpleExciter.a[1]", "Denominator coefficients of transfer function."\
, 0, 0.0,0.0,0.0,0,1)
DeclareVariable("SM2.AVR.SimpleExciter.a[2]", "Denominator coefficients of transfer function."\
, 1, 0.0,0.0,0.0,0,1)
DeclareState("SM2.AVR.SimpleExciter.x[1]", "State of transfer function from controller canonical form"\
, 25, 0, 0.0,0.0,0.0,0,0)
DeclareDerivative("SM2.AVR.SimpleExciter.der(x[1])", "State of transfer function from controller canonical form"\
, 0, 0.0,0.0,0.0,0,0)
DeclareVariable("SM2.AVR.SimpleExciter.na", "Size of Denominator of transfer function."\
, 2, 0.0,0.0,0.0,0,1)
DeclareVariable("SM2.AVR.SimpleExciter.nb", "Size of Numerator of transfer function."\
, 1, 0.0,0.0,0.0,0,1)
DeclareVariable("SM2.AVR.SimpleExciter.nx", "", 1, 0.0,0.0,0.0,0,1)
DeclareVariable("SM2.AVR.SimpleExciter.u", "", 0, 0.0,0.0,0.0,0,0)
DeclareParameter("KZ1.Bn", "", 68, (-100000), 0.0,0.0,0.0,0,0)
DeclareParameter("KZ1.TkzOn", "", 69, 1000, 0.0,0.0,0.0,0,0)
DeclareParameter("KZ1.dTkzOn", "", 70, 0.12, 0.0,0.0,0.0,0,0)
DeclareVariable("KZ1.id", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("KZ1.iq", "", 0, 0.0,0.0,0.0,0,0)
DeclareParameter("KZ2.Bn", "", 71, (-100000), 0.0,0.0,0.0,0,0)
DeclareParameter("KZ2.TkzOn", "", 72, 1000, 0.0,0.0,0.0,0,0)
DeclareParameter("KZ2.dTkzOn", "", 73, 0.12, 0.0,0.0,0.0,0,0)
DeclareVariable("KZ2.id", "", 0, 0.0,0.0,0.0,0,0)
DeclareVariable("KZ2.iq", "", 0, 0.0,0.0,0.0,0,0)
DeclareState("delta_G1_SM2", "", 26, 0, 0.0,0.0,0.0,0,0)
DeclareDerivative("der(delta_G1_SM2)", "", 0, 0.0,0.0,0.0,0,0)
EndNonAlias(0)

PreAlias(0)
StartAlias(0)
DeclareAlias("G1.G.dUtr", "", "G1.AVR.VoltageDeviation.u", 1, 5, 63)
DeclareAlias("G1.G.dWu", "", "G1.AVR.FrequencyBlockD.u", 1, 5, 78)
DeclareAlias("G1.G.dIf", "", "G1.AVR.ExcitationCurrent.u", 1, 5, 111)
DeclareAlias("G1.G.dWf", "", "G1.AVR.FrequencyBlockU.u", 1, 5, 85)
DeclareAlias("G1.G.UdG", "", "L0102.U1d", 1, 5, 119)
DeclareAlias("G1.G.UqG", "", "L0102.U1q", 1, 5, 120)
DeclareAlias("G1.G.IdG", "", "G1.G.id", 1, 5, 45)
DeclareAlias("G1.G.IqG", "", "G1.G.iq", 1, 5, 44)
DeclareAlias("G1.G.Ssys", "", "G1.G.s", 1, 1, 4)
DeclareAlias("G1.G.ud", "", "L0102.U1d", 1, 5, 119)
DeclareAlias("G1.G.uq", "", "L0102.U1q", 1, 5, 120)
DeclareAlias("G1.AVR.VoltageDeviation.x1dot", "Derivative of first state of TransferFcn"\
, "G1.AVR.VoltageDeviation.der(x[1])", 1, 6, 5)
DeclareAlias("G1.AVR.VoltageDeviation.xn", "Highest order state of TransferFcn"\
, "G1.AVR.VoltageDeviation.x[1]", 1, 1, 5)
DeclareAlias("G1.AVR.VoltageDerivative.x1dot", "Derivative of first state of TransferFcn"\
, "G1.AVR.VoltageDerivative.der(x[1])", 1, 6, 6)
DeclareAlias("G1.AVR.VoltageDerivative.xn", "Highest order state of TransferFcn"\
, "G1.AVR.VoltageDerivative.x[1]", 1, 1, 6)
DeclareAlias("G1.AVR.VoltageDerivative.u", "", "G1.AVR.VoltageDeviation.u", 1, 5\
, 63)
DeclareAlias("G1.AVR.FrequencyBlockD.x1dot", "Derivative of first state of TransferFcn"\
, "G1.AVR.FrequencyBlockD.der(x[1])", 1, 6, 7)
DeclareAlias("G1.AVR.FrequencyBlockD.xn", "Highest order state of TransferFcn"\
, "G1.AVR.FrequencyBlockD.x[1]", 1, 1, 7)
DeclareAlias("G1.AVR.FrequencyBlockU.x1dot", "Derivative of first state of TransferFcn"\
, "G1.AVR.FrequencyBlockU.der(x[1])", 1, 6, 8)
DeclareAlias("G1.AVR.FrequencyBlockU.xn", "Highest order state of TransferFcn"\
, "G1.AVR.FrequencyBlockU.x[1]", 1, 1, 8)
DeclareAlias("G1.AVR.FrequencyDeviation.x1dot", "Derivative of first state of TransferFcn"\
, "G1.AVR.FrequencyDeviation.der(x[1])", 1, 6, 9)
DeclareAlias("G1.AVR.FrequencyDeviation.xn", "Highest order state of TransferFcn"\
, "G1.AVR.FrequencyDeviation.x[1]", 1, 1, 9)
DeclareAlias("G1.AVR.FrequencyDerivative.x1dot", "Derivative of first state of TransferFcn"\
, "G1.AVR.FrequencyDerivative.der(x[1])", 1, 6, 10)
DeclareAlias("G1.AVR.FrequencyDerivative.xn", "Highest order state of TransferFcn"\
, "G1.AVR.FrequencyDerivative.x[1]", 1, 1, 10)
DeclareAlias("G1.AVR.FrequencyDerivative.u", "", "G1.AVR.FrequencyDeviation.u\
", 1, 5, 94)
DeclareAlias("G1.AVR.ExcitationCurrent.x1dot", "Derivative of first state of TransferFcn"\
, "G1.AVR.ExcitationCurrent.der(x[1])", 1, 6, 11)
DeclareAlias("G1.AVR.ExcitationCurrent.xn", "Highest order state of TransferFcn"\
, "G1.AVR.ExcitationCurrent.x[1]", 1, 1, 11)
DeclareAlias("G1.AVR.SimpleExciter.x1dot", "Derivative of first state of TransferFcn"\
, "G1.AVR.SimpleExciter.der(x[1])", 1, 6, 12)
DeclareAlias("G1.AVR.SimpleExciter.xn", "Highest order state of TransferFcn", "\
G1.AVR.SimpleExciter.x[1]", 1, 1, 12)
DeclareAlias("G1.AVR.SimpleExciter.y", "", "G1.G.dEr", 1, 5, 0)
DeclareAlias("G1.AVR.u_u", "", "G1.AVR.VoltageDeviation.u", 1, 5, 63)
DeclareAlias("G1.AVR.u_pu", "", "G1.AVR.VoltageDeviation.u", 1, 5, 63)
DeclareAlias("G1.AVR.u_fsys", "", "G1.AVR.FrequencyBlockD.u", 1, 5, 78)
DeclareAlias("G1.AVR.u_fu", "", "G1.AVR.FrequencyBlockU.u", 1, 5, 85)
DeclareAlias("G1.AVR.u_pIf", "", "G1.AVR.ExcitationCurrent.u", 1, 5, 111)
DeclareAlias("G1.AVR.y_er", "", "G1.G.dEr", 1, 5, 0)
DeclareAlias("G1.AVR.f_sum", "", "G1.AVR.FrequencyDeviation.u", 1, 5, 94)
DeclareAlias("L0102.Ssys", "", "G1.G.s", 1, 1, 4)
DeclareAlias("SM2.G.dUtr", "", "SM2.AVR.VoltageDeviation.u", 1, 5, 212)
DeclareAlias("SM2.G.dWu", "", "SM2.AVR.FrequencyBlockD.u", 1, 5, 227)
DeclareAlias("SM2.G.dIf", "", "SM2.AVR.ExcitationCurrent.u", 1, 5, 260)
DeclareAlias("SM2.G.dWf", "", "SM2.AVR.FrequencyBlockU.u", 1, 5, 234)
DeclareAlias("SM2.G.UdG", "", "L0102.U2d", 1, 5, 121)
DeclareAlias("SM2.G.UqG", "", "L0102.U2q", 1, 5, 122)
DeclareAlias("SM2.G.DeltaIJ", "", "delta_G1_SM2", 1, 1, 26)
DeclareAlias("SM2.G.Ssys", "", "G1.G.s", 1, 1, 4)
DeclareAlias("SM2.AVR.VoltageDeviation.x1dot", "Derivative of first state of TransferFcn"\
, "SM2.AVR.VoltageDeviation.der(x[1])", 1, 6, 18)
DeclareAlias("SM2.AVR.VoltageDeviation.xn", "Highest order state of TransferFcn"\
, "SM2.AVR.VoltageDeviation.x[1]", 1, 1, 18)
DeclareAlias("SM2.AVR.VoltageDerivative.x1dot", "Derivative of first state of TransferFcn"\
, "SM2.AVR.VoltageDerivative.der(x[1])", 1, 6, 19)
DeclareAlias("SM2.AVR.VoltageDerivative.xn", "Highest order state of TransferFcn"\
, "SM2.AVR.VoltageDerivative.x[1]", 1, 1, 19)
DeclareAlias("SM2.AVR.VoltageDerivative.u", "", "SM2.AVR.VoltageDeviation.u", 1\
, 5, 212)
DeclareAlias("SM2.AVR.FrequencyBlockD.x1dot", "Derivative of first state of TransferFcn"\
, "SM2.AVR.FrequencyBlockD.der(x[1])", 1, 6, 20)
DeclareAlias("SM2.AVR.FrequencyBlockD.xn", "Highest order state of TransferFcn"\
, "SM2.AVR.FrequencyBlockD.x[1]", 1, 1, 20)
DeclareAlias("SM2.AVR.FrequencyBlockU.x1dot", "Derivative of first state of TransferFcn"\
, "SM2.AVR.FrequencyBlockU.der(x[1])", 1, 6, 21)
DeclareAlias("SM2.AVR.FrequencyBlockU.xn", "Highest order state of TransferFcn"\
, "SM2.AVR.FrequencyBlockU.x[1]", 1, 1, 21)
DeclareAlias("SM2.AVR.FrequencyDeviation.x1dot", "Derivative of first state of TransferFcn"\
, "SM2.AVR.FrequencyDeviation.der(x[1])", 1, 6, 22)
DeclareAlias("SM2.AVR.FrequencyDeviation.xn", "Highest order state of TransferFcn"\
, "SM2.AVR.FrequencyDeviation.x[1]", 1, 1, 22)
DeclareAlias("SM2.AVR.FrequencyDerivative.x1dot", "Derivative of first state of TransferFcn"\
, "SM2.AVR.FrequencyDerivative.der(x[1])", 1, 6, 23)
DeclareAlias("SM2.AVR.FrequencyDerivative.xn", "Highest order state of TransferFcn"\
, "SM2.AVR.FrequencyDerivative.x[1]", 1, 1, 23)
DeclareAlias("SM2.AVR.FrequencyDerivative.u", "", "SM2.AVR.FrequencyDeviation.u\
", 1, 5, 243)
DeclareAlias("SM2.AVR.ExcitationCurrent.x1dot", "Derivative of first state of TransferFcn"\
, "SM2.AVR.ExcitationCurrent.der(x[1])", 1, 6, 24)
DeclareAlias("SM2.AVR.ExcitationCurrent.xn", "Highest order state of TransferFcn"\
, "SM2.AVR.ExcitationCurrent.x[1]", 1, 1, 24)
DeclareAlias("SM2.AVR.SimpleExciter.x1dot", "Derivative of first state of TransferFcn"\
, "SM2.AVR.SimpleExciter.der(x[1])", 1, 6, 25)
DeclareAlias("SM2.AVR.SimpleExciter.xn", "Highest order state of TransferFcn", "\
SM2.AVR.SimpleExciter.x[1]", 1, 1, 25)
DeclareAlias("SM2.AVR.SimpleExciter.y", "", "SM2.G.dEr", 1, 5, 146)
DeclareAlias("SM2.AVR.u_u", "", "SM2.AVR.VoltageDeviation.u", 1, 5, 212)
DeclareAlias("SM2.AVR.u_pu", "", "SM2.AVR.VoltageDeviation.u", 1, 5, 212)
DeclareAlias("SM2.AVR.u_fsys", "", "SM2.AVR.FrequencyBlockD.u", 1, 5, 227)
DeclareAlias("SM2.AVR.u_fu", "", "SM2.AVR.FrequencyBlockU.u", 1, 5, 234)
DeclareAlias("SM2.AVR.u_pIf", "", "SM2.AVR.ExcitationCurrent.u", 1, 5, 260)
DeclareAlias("SM2.AVR.y_er", "", "SM2.G.dEr", 1, 5, 146)
DeclareAlias("SM2.AVR.f_sum", "", "SM2.AVR.FrequencyDeviation.u", 1, 5, 243)
DeclareAlias("KZ1.Ud", "", "L0102.U1d", 1, 5, 119)
DeclareAlias("KZ1.Uq", "", "L0102.U1q", 1, 5, 120)
DeclareAlias("KZ2.Ud", "", "L0102.U2d", 1, 5, 121)
DeclareAlias("KZ2.Uq", "", "L0102.U2q", 1, 5, 122)
EndAlias(0)
#define NX_    27
#define NX2_   0
#define NU_    0
#define NY_    0
#define NW_    272
#define NP_    74
#define NRel_  12
#define NTim_  10
#define NSamp_ 0
#define NCons_ 0
#define NA_    76
#define SizePre_ 0
#define SizeEq_ 2
#define SizeDelay_ 0
#define QNLmax_ 0
#define MAXAux 0

#include <dsblock5.c>

StartDataBlock
StartEqBlock
DoRemember_(L0102_U2d, 0, 0);
DoRemember_(L0102_U2q, 0, 1);
EndEqBlock
EndDataBlock
