function dyn_in_create(exp,x0,p)

disp( '... Dymosim.m starts now -- dsin.txt correction' );
% Store data on dymosim input file
  matlabVersion = version;
  Aclass = [ 'Adymosim                   '
             '1.0                        '
             'Generated by Matlab/Dymosim' ];
  if matlabVersion(1,1)=='4' 
     if nargin < 1
        save dsin Aclass
     else
        experiment = exp';
        if nargin < 2
           save dsin Aclass experiment
        else
          [xx0, x_names] = initload;
          if nargin < 3
             save dsin Aclass experiment x_names x0
          else 
             [pp, param_names] = parload;
             param = p;
             save dsin Aclass experiment x_names x0 param_names param
          end
        end 
     end
  else
     if nargin > 0 & length(exp)==7
        eval(['! alist -b dsin.txt temp.mat |']);
        load temp
        delete temp.mat
        if nargin>0
           experiment=exp';
           if nargin>1
              I=find(initialValue(:,5)==2);
              initialValue(I,2)=x0(:);
              if nargin>2
                 I=find(initialValue(:,5)==1);
                 initialValue(I,2)=p(:);
              end;
           end;
        end;
        save dsin Aclass experiment method settings initialName initialValue -v4
     else
     save dsin Aclass -v4;
     if nargin > 0
        experiment = exp';
        save dsin experiment -v4 -append;
        if nargin > 1
          [xx0, x_names] = initload;
          save dsin x_names -v4 -append;
          save dsin x0 -v4 -append;
          if nargin > 2
             [pp, param_names] = parload;
             param = p;
             save dsin param_names -v4 -append;
             save dsin param -v4 -append;
          end
        end 
     end
     end
  end 
 

% Run dymosim
disp( '... Dymosim.m starts now -- dsin.txt correction finished!!!' );
